### PR TITLE
Remove Data suffix according to review comments.

### PR DESCRIPTION
**Pull request by katmsft**
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/master/CONTRIBUTING.md#pull-requests).

- [x] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [x] Doxygen docs
- [x] Unit tests
- [x] No unwanted commits/changes
- [x] Descriptive title/description
  - [x] PR is single purpose
  - [x] Related issue listed
- [x] Comments in source
- [x] No typos
- [x] Update changelog
- [x] Not work-in-progress
- [x] External references or docs updated
- [x] Self review of PR done
- [x] Any breaking changes?

### CODE REVIEW

**Comment by Jinming-Hu** [comment]
Add you add a reference to the review comment?

**Comment by katmsft** [comment]
https://apiview.dev/Assemblies/Review/5aec114a35f946ba9ee31e0955b69fea/3f7968969c174453b73253d6aef57c01#Azure::Storage::Files::DataLake::FileClient.AppendData:Azure::Core::Http::BodyStream_*:int64_t:const_Azure::Storage::Files::DataLake::AppendFileDataOptions_&::Azure::Core::Response%3CModels::AppendFileDataResult%3E

**Comment by Jinming-Hu** [comment]
> https://apiview.dev/Assemblies/Review/5aec114a35f946ba9ee31e0955b69fea/3f7968969c174453b73253d6aef57c01#Azure::Storage::Files::DataLake::FileClient.AppendData:Azure::Core::Http::BodyStream_*:int64_t:const_Azure::Storage::Files::DataLake::AppendFileDataOptions_&::Azure::Core::Response%3CModels::AppendFileDataResult%3E

I see Ted's comment

> The return type name looks wrong? In .NET we user [Method]Result when it's a very unique method or [Class][Method]Result when it's generic sounding like Blob's GetProperties vs. Container's GetProperties. It seems you're using [Method][Class]Result most places, but here you've stuck the File between the Append and Data. Ditto for the parameters and the other methods where you added Data.

So which patter are you following for Append and Flush API? @katmsft

**Comment by katmsft** [comment]
> > https://apiview.dev/Assemblies/Review/5aec114a35f946ba9ee31e0955b69fea/3f7968969c174453b73253d6aef57c01#Azure::Storage::Files::DataLake::FileClient.AppendData:Azure::Core::Http::BodyStream_*:int64_t:const_Azure::Storage::Files::DataLake::AppendFileDataOptions_&::Azure::Core::Response%3CModels::AppendFileDataResult%3E
> 
> I see Ted's comment
> 
> > The return type name looks wrong? In .NET we user [Method]Result when it's a very unique method or [Class][Method]Result when it's generic sounding like Blob's GetProperties vs. Container's GetProperties. It seems you're using [Method][Class]Result most places, but here you've stuck the File between the Append and Data. Ditto for the parameters and the other methods where you added Data.
> 
> So which pattern are you following for Append and Flush API? @katmsft

This is another topic. Until we get it finalized I'm going to honor the previous pattern, which is [Method][Resource]Result.

**Comment by Jinming-Hu** [comment]
> > > https://apiview.dev/Assemblies/Review/5aec114a35f946ba9ee31e0955b69fea/3f7968969c174453b73253d6aef57c01#Azure::Storage::Files::DataLake::FileClient.AppendData:Azure::Core::Http::BodyStream_*:int64_t:const_Azure::Storage::Files::DataLake::AppendFileDataOptions_&::Azure::Core::Response%3CModels::AppendFileDataResult%3E
> > 
> > 
> > I see Ted's comment
> > > The return type name looks wrong? In .NET we user [Method]Result when it's a very unique method or [Class][Method]Result when it's generic sounding like Blob's GetProperties vs. Container's GetProperties. It seems you're using [Method][Class]Result most places, but here you've stuck the File between the Append and Data. Ditto for the parameters and the other methods where you added Data.
> > 
> > 
> > So which pattern are you following for Append and Flush API? @katmsft
> 
> This is another topic. Until we get it finalized I'm going to honor the previous pattern, which is [Method][Resource]Result.

So what is [Resource] here? Since you changed it to `FlushDataLakeFileOptions`, I'd assume [Resource] here is `DataLakeFile`. If this is the case, how should we name the options or result types for `DataLakeDirectoryClient::SetAccessControl`? `SetDataLakeDirectoryOptions`?

**Comment by katmsft** [comment]
> SetDataLakeDirectoryOptions

Sorry the pattern is `<Verb><Model><Preposition>Result` to be more precise.
No, it should be `SetDataLakeDirectoryAccessControlOptions`, if the model is `DataLakeDirectoryAccessControl` or `SetAccessControlOptions` if `AccessControl` is a more broader model shared by multiple resource.

**Comment by Jinming-Hu** [comment]
> > SetDataLakeDirectoryOptions
> 
> Sorry the pattern is `<Verb><Model><Preposition>Result` to be more precise.
> No, it should be `SetDataLakeDirectoryAccessControlOptions`, if the model is `DataLakeDirectoryAccessControl` or `SetAccessControlOptions` if `AccessControl` is a more broader model shared by multiple resource.

What's \<Preposition\>?

**Comment by katmsft** [comment]
> > > SetDataLakeDirectoryOptions
> > 
> > 
> > Sorry the pattern is `<Verb><Model><Preposition>Result` to be more precise.
> > No, it should be `SetDataLakeDirectoryAccessControlOptions`, if the model is `DataLakeDirectoryAccessControl` or `SetAccessControlOptions` if `AccessControl` is a more broader model shared by multiple resource.
> 
> What's <Preposition>?

It's in some APIs like `DownloadTo` and `UploadFrom`, to/from are the propositions.

**Comment by Jinming-Hu** [comment]
> > > > SetDataLakeDirectoryOptions
> > > 
> > > 
> > > Sorry the pattern is `<Verb><Model><Preposition>Result` to be more precise.
> > > No, it should be `SetDataLakeDirectoryAccessControlOptions`, if the model is `DataLakeDirectoryAccessControl` or `SetAccessControlOptions` if `AccessControl` is a more broader model shared by multiple resource.
> > 
> > 
> > What's ?
> 
> It's in some APIs like `DownloadTo` and `UploadFrom`, to/from are the prepositions.

And what's the \<Model\>?

**Comment by katmsft** [comment]
> > > > > SetDataLakeDirectoryOptions
> > > > 
> > > > 
> > > > Sorry the pattern is `<Verb><Model><Preposition>Result` to be more precise.
> > > > No, it should be `SetDataLakeDirectoryAccessControlOptions`, if the model is `DataLakeDirectoryAccessControl` or `SetAccessControlOptions` if `AccessControl` is a more broader model shared by multiple resource.
> > > 
> > > 
> > > What's ?
> > 
> > 
> > It's in some APIs like `DownloadTo` and `UploadFrom`, to/from are the prepositions.
> 
> And what's the <Model>?

It's the resource this verb targets.

**Comment by Jinming-Hu** [comment]
> > > > > > SetDataLakeDirectoryOptions
> > > > > 
> > > > > 
> > > > > Sorry the pattern is `<Verb><Model><Preposition>Result` to be more precise.
> > > > > No, it should be `SetDataLakeDirectoryAccessControlOptions`, if the model is `DataLakeDirectoryAccessControl` or `SetAccessControlOptions` if `AccessControl` is a more broader model shared by multiple resource.
> > > > 
> > > > 
> > > > What's ?
> > > 
> > > 
> > > It's in some APIs like `DownloadTo` and `UploadFrom`, to/from are the prepositions.
> > 
> > 
> > And what's the ?
> 
> It's the resource this verb targets.

So according to this theory, the option for `DataLakeDirectoryClient::SetAccessControl` should be `SetDataLakeDirectoryOptions`, is that correct?

**Comment by katmsft** [comment]
> > > > > > > SetDataLakeDirectoryOptions
> > > > > > 
> > > > > > 
> > > > > > Sorry the pattern is `<Verb><Model><Preposition>Result` to be more precise.
> > > > > > No, it should be `SetDataLakeDirectoryAccessControlOptions`, if the model is `DataLakeDirectoryAccessControl` or `SetAccessControlOptions` if `AccessControl` is a more broader model shared by multiple resource.
> > > > > 
> > > > > 
> > > > > What's ?
> > > > 
> > > > 
> > > > It's in some APIs like `DownloadTo` and `UploadFrom`, to/from are the prepositions.
> > > 
> > > 
> > > And what's the ?
> > 
> > 
> > It's the resource this verb targets.
> 
> So according to this theory, the option for `DataLakeDirectoryClient::SetAccessControl` should be `SetDataLakeDirectoryOptions`, is that correct?

No, the resource this API targets is the `DataLakeDirectoryAccessControl` or `AccessControl`.

**Comment by Jinming-Hu** [comment]
> > > > > > > > SetDataLakeDirectoryOptions
> > > > > > > 
> > > > > > > 
> > > > > > > Sorry the pattern is `<Verb><Model><Preposition>Result` to be more precise.
> > > > > > > No, it should be `SetDataLakeDirectoryAccessControlOptions`, if the model is `DataLakeDirectoryAccessControl` or `SetAccessControlOptions` if `AccessControl` is a more broader model shared by multiple resource.
> > > > > > 
> > > > > > 
> > > > > > What's ?
> > > > > 
> > > > > 
> > > > > It's in some APIs like `DownloadTo` and `UploadFrom`, to/from are the prepositions.
> > > > 
> > > > 
> > > > And what's the ?
> > > 
> > > 
> > > It's the resource this verb targets.
> > 
> > 
> > So according to this theory, the option for `DataLakeDirectoryClient::SetAccessControl` should be `SetDataLakeDirectoryOptions`, is that correct?
> 
> No, the resource this API targets is the `DataLakeDirectoryAccessControl` or `AccessControl`.

Then what's the resource for Flush and Append?

**Comment by katmsft** [comment]
> > > > > > > > > SetDataLakeDirectoryOptions
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Sorry the pattern is `<Verb><Model><Preposition>Result` to be more precise.
> > > > > > > > No, it should be `SetDataLakeDirectoryAccessControlOptions`, if the model is `DataLakeDirectoryAccessControl` or `SetAccessControlOptions` if `AccessControl` is a more broader model shared by multiple resource.
> > > > > > > 
> > > > > > > 
> > > > > > > What's ?
> > > > > > 
> > > > > > 
> > > > > > It's in some APIs like `DownloadTo` and `UploadFrom`, to/from are the prepositions.
> > > > > 
> > > > > 
> > > > > And what's the ?
> > > > 
> > > > 
> > > > It's the resource this verb targets.
> > > 
> > > 
> > > So according to this theory, the option for `DataLakeDirectoryClient::SetAccessControl` should be `SetDataLakeDirectoryOptions`, is that correct?
> > 
> > 
> > No, the resource this API targets is the `DataLakeDirectoryAccessControl` or `AccessControl`.
> 
> Then what's the resource for Flush and Append?

It is actually `FlushTo` or `AppendTo` from what I understand, the resource is `DataLakeFile`, however if I change to `FlushTo` then it won't be consistent with what .NET have now so I have no good ways for it.

**Comment by Jinming-Hu** [comment]
> > > > > > > > > > SetDataLakeDirectoryOptions
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Sorry the pattern is `<Verb><Model><Preposition>Result` to be more precise.
> > > > > > > > > No, it should be `SetDataLakeDirectoryAccessControlOptions`, if the model is `DataLakeDirectoryAccessControl` or `SetAccessControlOptions` if `AccessControl` is a more broader model shared by multiple resource.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > What's ?
> > > > > > > 
> > > > > > > 
> > > > > > > It's in some APIs like `DownloadTo` and `UploadFrom`, to/from are the prepositions.
> > > > > > 
> > > > > > 
> > > > > > And what's the ?
> > > > > 
> > > > > 
> > > > > It's the resource this verb targets.
> > > > 
> > > > 
> > > > So according to this theory, the option for `DataLakeDirectoryClient::SetAccessControl` should be `SetDataLakeDirectoryOptions`, is that correct?
> > > 
> > > 
> > > No, the resource this API targets is the `DataLakeDirectoryAccessControl` or `AccessControl`.
> > 
> > 
> > Then what's the resource for Flush and Append?
> 
> It is actually `FlushTo` or `AppendTo` from what I understand, the resource is `DataLakeFile`, however if I change to `FlushTo` then it won't be consistent with what .NET have now so I have no good ways for it.

I do not understand, it's not like `DownloadTo`, where we download the resource (blob or file) to somewhere (memory or disk).
If it is`FlushTo`, we flush what to what?

**Comment by katmsft** [comment]
> > > > > > > > > > > SetDataLakeDirectoryOptions
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Sorry the pattern is `<Verb><Model><Preposition>Result` to be more precise.
> > > > > > > > > > No, it should be `SetDataLakeDirectoryAccessControlOptions`, if the model is `DataLakeDirectoryAccessControl` or `SetAccessControlOptions` if `AccessControl` is a more broader model shared by multiple resource.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > What's ?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It's in some APIs like `DownloadTo` and `UploadFrom`, to/from are the prepositions.
> > > > > > > 
> > > > > > > 
> > > > > > > And what's the ?
> > > > > > 
> > > > > > 
> > > > > > It's the resource this verb targets.
> > > > > 
> > > > > 
> > > > > So according to this theory, the option for `DataLakeDirectoryClient::SetAccessControl` should be `SetDataLakeDirectoryOptions`, is that correct?
> > > > 
> > > > 
> > > > No, the resource this API targets is the `DataLakeDirectoryAccessControl` or `AccessControl`.
> > > 
> > > 
> > > Then what's the resource for Flush and Append?
> > 
> > 
> > It is actually `FlushTo` or `AppendTo` from what I understand, the resource is `DataLakeFile`, however if I change to `FlushTo` then it won't be consistent with what .NET have now so I have no good ways for it.
> 
> I do not understand, it's not like `DownloadTo`, where we download the resource (blob or file) to somewhere (memory or disk).
> If it is`FlushTo`, we flush what to what?

The full name should be `FlushUncommittedDataToFile` and `AppendDataToFile`.

**Comment by Jinming-Hu** [comment]
> > > > > > > > > > > > SetDataLakeDirectoryOptions
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > Sorry the pattern is `<Verb><Model><Preposition>Result` to be more precise.
> > > > > > > > > > > No, it should be `SetDataLakeDirectoryAccessControlOptions`, if the model is `DataLakeDirectoryAccessControl` or `SetAccessControlOptions` if `AccessControl` is a more broader model shared by multiple resource.
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > What's ?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > It's in some APIs like `DownloadTo` and `UploadFrom`, to/from are the prepositions.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > And what's the ?
> > > > > > > 
> > > > > > > 
> > > > > > > It's the resource this verb targets.
> > > > > > 
> > > > > > 
> > > > > > So according to this theory, the option for `DataLakeDirectoryClient::SetAccessControl` should be `SetDataLakeDirectoryOptions`, is that correct?
> > > > > 
> > > > > 
> > > > > No, the resource this API targets is the `DataLakeDirectoryAccessControl` or `AccessControl`.
> > > > 
> > > > 
> > > > Then what's the resource for Flush and Append?
> > > 
> > > 
> > > It is actually `FlushTo` or `AppendTo` from what I understand, the resource is `DataLakeFile`, however if I change to `FlushTo` then it won't be consistent with what .NET have now so I have no good ways for it.
> > 
> > 
> > I do not understand, it's not like `DownloadTo`, where we download the resource (blob or file) to somewhere (memory or disk).
> > If it is`FlushTo`, we flush what to what?
> 
> The full name should be `FlushUncommittedDataToFile` and `AppendDataToFile`. Since `Data` in these names are not in favor so they are removed. It then becomes `FlushToFile` and `AppendToFile`.

So analogously, the full name `SetAccessControlListToDirectory` should be `SetToDirectory`, correct?

**Comment by katmsft** [comment]
> > > > > > > > > > > > > SetDataLakeDirectoryOptions
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > Sorry the pattern is `<Verb><Model><Preposition>Result` to be more precise.
> > > > > > > > > > > > No, it should be `SetDataLakeDirectoryAccessControlOptions`, if the model is `DataLakeDirectoryAccessControl` or `SetAccessControlOptions` if `AccessControl` is a more broader model shared by multiple resource.
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > What's ?
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > It's in some APIs like `DownloadTo` and `UploadFrom`, to/from are the prepositions.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > And what's the ?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It's the resource this verb targets.
> > > > > > > 
> > > > > > > 
> > > > > > > So according to this theory, the option for `DataLakeDirectoryClient::SetAccessControl` should be `SetDataLakeDirectoryOptions`, is that correct?
> > > > > > 
> > > > > > 
> > > > > > No, the resource this API targets is the `DataLakeDirectoryAccessControl` or `AccessControl`.
> > > > > 
> > > > > 
> > > > > Then what's the resource for Flush and Append?
> > > > 
> > > > 
> > > > It is actually `FlushTo` or `AppendTo` from what I understand, the resource is `DataLakeFile`, however if I change to `FlushTo` then it won't be consistent with what .NET have now so I have no good ways for it.
> > > 
> > > 
> > > I do not understand, it's not like `DownloadTo`, where we download the resource (blob or file) to somewhere (memory or disk).
> > > If it is`FlushTo`, we flush what to what?
> > 
> > 
> > The full name should be `FlushUncommittedDataToFile` and `AppendDataToFile`. Since `Data` in these names are not in favor so they are removed. It then becomes `FlushToFile` and `AppendToFile`.
> 
> So analogously, the full name `SetAccessControlListToDirectory` should be `SetToDirectory`, correct?

In this case `SetTo` if someone from arch board complains about `AccessControlList` and asked me to remove it.

**Comment by katmsft** [comment]
@Jinming-Hu You definitely are very concerned about something in this PR, but after ~20 conversations I still don't quite get what's your point. Can you please clarify on what point you are trying to make here? Maybe it is more efficient to address it in this way.

**Comment by Jinming-Hu** [comment]
> @Jinming-Hu You definitely are very concerned about something in this PR, but after ~20 conversations I still don't quite get what's your point. Can you please clarify on what point you are trying to make here? Maybe it is more efficient to address it in this way.

I don't know, I just find the name is kind of weird, or maybe inconsistent?

**Comment by katmsft** [comment]
I agree the API name itself is inconsistent after it is changed according to the review comment. The result/options names are just suffering from this inconsistency.

**Comment by Jinming-Hu** [comment]
> I agree the API name itself is inconsistent after it is changed according to the review comment. The result/options names are just suffering from this inconsistency.

I dont know. Whatever

**Review by Jinming-Hu — APPROVED** [review]

**Pull request merged**
