### PR TITLE
Address gcc13 compilation issue

### PR DESCRIPTION
**Pull request by adamdebreceni**
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Comment by ahsonkhan** [comment]
Thanks for the fix. The change itself looks reasonable, but one concern is that unless we introduce that compiler as a check in the CI pipeline or some other testing mechanism, there's nothing preventing the errors to come back (or appear in new files). I think we'd want to address that first, to always remain green.

**Review by RickWinter — APPROVED** [review]

**Comment by LarryOsterman** [comment]
@adamdebreceni, would you mind approving the contributor licence agreement? 

Your change looks good to us, but we need you to complete the agreement before we can commit your changes to our repository.

**Comment by ahsonkhan** [comment]
@adamdebreceni please let us know if you need help with approving the contributor license agreement. We'd like to get this change in since you made this improvement. We have others making a similar contribution (for example by @kou here: https://github.com/Azure/azure-sdk-for-cpp/pull/4897).

**Comment by adamdebreceni** [comment]
> @adamdebreceni please let us know if you need help with approving the contributor license agreement. We'd like to get this change in since you made this improvement. We have others making a similar contribution (for example by @kou here: #4897).

how do I approve the contributor license agreement?

**Comment by adamdebreceni** [comment]
@microsoft-github-policy-service agree

**Comment by ahsonkhan** [comment]
Looks like you were able to figure it out how :)
Thanks!

https://github.com/microsoft/contributorlicenseagreement#commands

**Comment by LarryOsterman** [comment]
Thank you so much for your contribution.

**Pull request merged**
