### PR TITLE
Avoid using WinHttpQueryDataAvailable, and use WinHttpReadData directly for better throughput.

### PR DESCRIPTION
**Pull request by ahsonkhan**
Performance optimization for download, as part of https://github.com/Azure/azure-sdk-for-cpp/issues/1201, especially for large payloads.

~Will share performance numbers soon, but local testing showed promise.~
image

Avg of 6   (ops/s) | 5 | 10 KiB | 10 MiB | 1 GiB (8) | 1 GiB (32)
-- | -- | -- | -- | -- | --
Before | 173.00 | 179.67 | 209.00 | 1.15 | 3.67
After | 168.83 | 176.17 | 228.33 | 1.78 | 5.51
Ratio | 0.98 | 0.98 | 1.09 | 1.55 | 1.50

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@Jinming-Hu can you please re-run your benchmark against this change and see if you also see a 10%+ improvement in perf for download?

**Comment by ahsonkhan** [comment]
Also, looks like there is some intermittent (unrelated) linux live test failure:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=887515&view=logs&j=b28a1a35-334b-5681-3876-e5562b5e8062&t=8093ec4b-94b5-5b1c-251c-634eb19c00d0&l=408
```text
2021-05-11T00:00:16.9351667Z 294: [ RUN      ] BlobServiceClientTest.UndeleteBlobContainer
2021-05-11T00:00:16.9693168Z 294: unknown file: Failure
2021-05-11T00:00:16.9695340Z 294: C++ exception with description "400 The value of deleted-container-name header must match the destination container name.
2021-05-11T00:00:16.9696803Z 294: The value of deleted-container-name header must match the destination container name.
2021-05-11T00:00:16.9698383Z 294: RequestId:78f0dd6f-201e-0069-6cf8-459a55000000
2021-05-11T00:00:16.9699893Z 294: Time:2021-05-11T00:00:16.9702517Z
2021-05-11T00:00:16.9701374Z 294: Request ID: 78f0dd6f-201e-0069-6cf8-459a55000000" thrown in the test body.
2021-05-11T00:00:16.9702588Z 294: [  FAILED  ] BlobServiceClientTest.UndeleteBlobContainer (34 ms)
```

**Review by antkmsft — APPROVED** [review]

**Review by vhvb1989 — APPROVED** [review]

**Review by Jinming-Hu — APPROVED** [review]

**Comment by ahsonkhan** [comment]
I verified on the same VM as the reported, in release, and the numbers are similar.
We get a pretty big perf boost for large payloads, now track2 winhttp is 20%+ faster for large payloads :)

Investigation for the ~10% drop in small payloads is pending, but so far, that might just be difference between libcurl/winhttp, so don't have great ideas for fixing low hanging fruit there.

image

**Pull request merged**
