### PR TITLE
Consolidate the use of std::size_t and always use size_t instead, since it is a "primitive" type.

### PR DESCRIPTION
**Pull request by ahsonkhan**
Fixes the azure core and keyvault parts of https://github.com/Azure/azure-sdk-for-cpp/issues/2319

We don't have an instances of types like `std::[u]int`, and functions like `std::memcpy` can remain as is. Left other things, within storage, like `ptrdiff_t` to be fixed separately.

### CODE REVIEW

**Comment by antkmsft** [comment]
I think we should go the other way, and to use C++ types and not C types. We should replace c-style headers like `#include <stdint.h>` with `#include <cstdint>`, refer to size_t as `std::size_t`, and (u)intN_t as `std::_(u)intN_t`.

**Comment by antkmsft** [comment]
BTW, for the includes, we should do that foar all stdlib includes - i.e. `#include <cstdio>` instead of `stdio.h`, and if there are more, do the same for them as well.

**Comment by ahsonkhan** [comment]
> I think we should go the other way, and to use C++ types and not C types. We should replace c-style headers like `#include <stdint.h>` with `#include <cstdint>`, refer to size_t as `std::size_t`, and (u)intN_t as `std::_(u)intN_t`.

We had this discussion in other threads previously, we have converged moreso towards size_t instead, so this is just completing the few leftover places. I prefer not to revert the direction at this point, doesn't seem worth the effort for a customer impact perspective.
Feel free to read the previous discussion starting from https://github.com/Azure/azure-sdk-for-cpp/pull/2285#pullrequestreview-661558933

> BTW, for the includes, we should do that foar all stdlib includes - i.e. `#include <cstdio>` instead of `stdio.h`, and if there are more, do the same for them as well.

That's a separate issue, I have no strong opinion either way, up to you. From previous discussions with C++ folks, there is no clear consensus, so to me, this issue/fix doesn't meet the bar to spend a lot of time on, we can work on more impactful features and bug fixes :)

**Review by Jinming-Hu — APPROVED** [review]

**Comment by Jinming-Hu** [comment]
> > I think we should go the other way, and to use C++ types and not C types. We should replace c-style headers like `#include <stdint.h>` with `#include <cstdint>`, refer to size_t as `std::size_t`, and (u)intN_t as `std::_(u)intN_t`.
> 
> We had this discussion in other threads previously, we have converged moreso towards size_t instead, so this is just completing the few leftover places. I prefer not to revert the direction at this point, doesn't seem worth the effort for a customer impact perspective.
> Feel free to read the previous discussion starting from [#2285 (review)](https://github.com/Azure/azure-sdk-for-cpp/pull/2285#pullrequestreview-661558933)
> 
> > BTW, for the includes, we should do that foar all stdlib includes - i.e. `#include <cstdio>` instead of `stdio.h`, and if there are more, do the same for them as well.
> 
> That's a separate issue, I have no strong opinion either way, up to you. From previous discussions with C++ folks, there is no clear consensus, so to me, this issue/fix doesn't meet the bar to spend a lot of time on, we can work on more impactful features and bug fixes :)

Yes, this is a separate issue. And I'd vote for `<cstdio>`.

**Review by vhvb1989 — APPROVED** [review]

**Pull request merged**
