### PR TITLE
adding-nlohmann-3.6-to-interna-core-headers

### PR DESCRIPTION
**Pull request by vhvb1989**
Adding the original nlohmann main header to internal API so it is easier to see any futher changes made to it while adapting it

### CODE REVIEW

**Comment by Jinming-Hu** [comment]
@vhvb1989 Why you included this header into core sdk again? I remember it was in core, then removed.

**Comment by ahsonkhan** [comment]
This is a verbatim copy of version 3.6.0 from https://github.com/nlohmann/json/blob/51e1564c9e61c91c724503496a6c90e54eb591cc/single_include/nlohmann/json.hpp

Should we consider making this a git submodule?

**Comment by vhvb1989** [comment]
> Should we consider making this a git submodule to avoid having large files in our git tree?

The intention is to have this file updated in order to be functional for us. Can't really use submodules for this

**Review by ahsonkhan — APPROVED** [review]

**Comment by antkmsft** [comment]
@vhvb1989 , you added the public macros below to the public header. Even though it is internal, when it is included by any of our public headers, it is going to define the macros below.

Please get rid of most of them, and for these which are impossible to remove, please prefix with `AZ_`. They would interfere with user's code (specifically, with the actual Nlohmann Json.

```
#define INCLUDE_NLOHMANN_JSON_HPP_ - replace with #pragma once
#define INCLUDE_NLOHMANN_JSON_FWD_HPP_ - remove

#define NLOHMANN_JSON_VERSION_MAJOR 3 - get rid of the macro, find and replace with actual value
#define NLOHMANN_JSON_VERSION_MINOR 6 - get rid of the macro, find and replace with actual value
#define NLOHMANN_JSON_VERSION_PATCH 0 - get rid of the macro, find and replace with actual value

#define JSON_DEPRECATED - remove

#define JSON_NODISCARD - remove

#define JSON_THROW - get rid of the macro, find and replace with actual value
#define JSON_TRY - get rid of the macro, find and replace with actual value
#define JSON_CATCH - get rid of the macro, find and replace with actual value
#define JSON_INTERNAL_CATCH - get rid of the macro, find and replace with actual value
#define JSON_LIKELY - get rid of the macro, find and replace with actual value
#define JSON_UNLIKELY - get rid of the macro, find and replace with actual value
#define JSON_HAS_CPP_17 - remove
#define JSON_HAS_CPP_14- remove

#define NLOHMANN_JSON_SERIALIZE_ENUM
   - prefix with AZ_, if only used in implementation - move there, or find and replace with the actual value

#define NLOHMANN_BASIC_JSON_TPL_DECLARATION
   - prefix with AZ_, if only used in implementation - move there, or find and replace with the actual value

#define NLOHMANN_BASIC_JSON_TPL
   - prefix with AZ_, if only used in implementation - move there, or find and replace with the actual value
```

**Comment by vhvb1989** [comment]
> 
> 
> @vhvb1989 , you added the public macros below to the public header. Even though it is internal, when it is included by any of our public headers, it is going to define the macros below.
> 
> Please get rid of most of them, and for these which are impossible to remove, please prefix with `AZ_`. They would interfere with user's code (specifically, with the actual Nlohmann Json.
> 
> ```
> #define INCLUDE_NLOHMANN_JSON_HPP_ - replace with #pragma once
> #define INCLUDE_NLOHMANN_JSON_FWD_HPP_ - remove
> 
> #define NLOHMANN_JSON_VERSION_MAJOR 3 - get rid of the macro, find and replace with actual value
> #define NLOHMANN_JSON_VERSION_MINOR 6 - get rid of the macro, find and replace with actual value
> #define NLOHMANN_JSON_VERSION_PATCH 0 - get rid of the macro, find and replace with actual value
> 
> #define JSON_DEPRECATED - remove
> 
> #define JSON_NODISCARD - remove
> 
> #define JSON_THROW - get rid of the macro, find and replace with actual value
> #define JSON_TRY - get rid of the macro, find and replace with actual value
> #define JSON_CATCH - get rid of the macro, find and replace with actual value
> #define JSON_INTERNAL_CATCH - get rid of the macro, find and replace with actual value
> #define JSON_LIKELY - get rid of the macro, find and replace with actual value
> #define JSON_UNLIKELY - get rid of the macro, find and replace with actual value
> #define JSON_HAS_CPP_17 - remove
> #define JSON_HAS_CPP_14- remove
> 
> #define NLOHMANN_JSON_SERIALIZE_ENUM
>    - prefix with AZ_, if only used in implementation - move there, or find and replace with the actual value
> 
> #define NLOHMANN_BASIC_JSON_TPL_DECLARATION
>    - prefix with AZ_, if only used in implementation - move there, or find and replace with the actual value
> 
> #define NLOHMANN_BASIC_JSON_TPL
>    - prefix with AZ_, if only used in implementation - move there, or find and replace with the actual value
> ```

Yes, on the next PR #1378 I changed the guards for pragma once.
This file was added just to keep the original version without any modifications to our source code.

Thank you!

**Comment by antkmsft** [comment]
@vhvb1989, you only removed one of them, the rest are still there, and the recent PR introduces way more of them. I left the feedback for the active PR to get rid of all them. We can't have them in a header that gets included from our public headers.

**Pull request merged**
