### PR TITLE
Initial cut at AMQP protocol implementation.

### PR DESCRIPTION
**Pull request by LarryOsterman**
# Initial implementation of AMQP protocol.

There is still a great deal of cleanup that needs to be done before this is complete, but there is enough present to enable development of an AMQP client.

## Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Comment by LarryOsterman** [comment]
This is the same PR as the previous one, but namespaces are cleaned up. Please take a look at it.

**Comment by LarryOsterman** [comment]
Approval would be appreciated at some point :).

**Review by antkmsft — APPROVED** [review]
I am going to approve the PR, because it blocks you, and also it is true that it goes to a feature branch, but I'd really like for us to be able to review it and to apply what we find, because there won't be another change to look at this change as a whole.

**Comment by LarryOsterman** [comment]
> I am going to approve the PR, because it blocks you, and also it is true that it goes to a feature branch, but I'd really like for us to be able to review it and to apply what we find, because there won't be another change to look at this change as a whole.

When the AMQP feature branch merges with main, you'll get to see the entire payload once again.

**Pull request merged**
