### PR TITLE
Update vcpkg SHA

### PR DESCRIPTION
**Pull request by antkmsft**
Nothing urgent, it is just to update from the July SHA, we should do it periodically.
I want to merge this before the Core release, so that the change gets auto-pushed to the Betas registry with the release.

### CODE REVIEW

**Review by LarryOsterman — APPROVED** [review]

**Comment by ahsonkhan** [comment]
@antkmsft can you help me understand why we'd want to do this periodically? What's the outcome of updating the vcpkg baseline?
And how does it impact the beta registry?

**Comment by LarryOsterman** [comment]
> @antkmsft can you help me understand why we'd want to do this periodically? What's the outcome of updating the vcpkg baseline? And how does it impact the beta registry?

Chiming in a bit: IMHO we should be updating the vcpkg baseline at least once every quarter and preferably once each month.

Otherwise, we are testing against older versions of our dependent packages. We've seen problems in the C++ repo caused by tools which are built from out-of-date packages.

**Comment by antkmsft** [comment]
@ahsonkhan, Larry has put it very well. As of "how does it impact the beta registry" - there is a baseline in the vcpkg-configuration.json: https://github.com/Azure/azure-sdk-vcpkg-betas/blob/main/vcpkg-configuration.json#L4 . And each time we release, vcpkg-betas gets updated, and there is a functionality to take the vcpkg SHA from our repo and update vcpkg SHA in that vcpkg-configuration.json each time during the release (#5330).

**Pull request merged**
