### PR TITLE
Fix StartCopyBlobOperation by removing the field - derived classes should not define a member with the same type and name as the base class

### PR DESCRIPTION
**Pull request by vhvb1989**

### CODE REVIEW

**Review by ahsonkhan — APPROVED** [review]

**Comment by ahsonkhan** [comment]
From https://github.com/Azure/azure-sdk-for-cpp/pull/1875

**Review by RickWinter — APPROVED** [review]

**Comment by ahsonkhan** [comment]
GitHub UI is not updating but the build pipelines are passing:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=780577&view=results

**Pull request merged**
