### PR TITLE
First attempt at fixing nlohmann doctest compilation error

### PR DESCRIPTION
**Pull request by LarryOsterman**
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Comment by vhvb1989** [comment]
Do we have an issue for this?
What is what we are trying to fix?  
We did not need to update this tests (as it is external) in the past.  So, wondering why we need to touch those files now...

**Comment by vhvb1989** [comment]
might be worth it to consider updating the nlohmann json lib to a newer version.

**Comment by LarryOsterman** [comment]
> @vhvb1989 -- This is to fix a complier error we're encountering in this PR: #4442
> 
> This is the error we're seeing: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2667957&view=logs&j=ee76c233-a59e-5872-c34c-b9843bcc71ea&t=7df4bab8-9439-5dda-1896-ba94748419f5

Basically, on Ubuntu 2022, the SIGSTKSZ value stopped being a constant and turned into a function call. This change picks up the minimal set of changes necessary to get the doctest.h file to continue to work.

IMHO resyncing nlohmann.json is a great idea, but this is all about fixing our pipelines in front of a monday shutdown of Ubuntu 18 images.

**Review by vhvb1989 — APPROVED** [review]

**Comment by vhvb1989** [comment]
Just noticed that `doctest` is a library and we are consuming an auto-generated .h file.

I created this other approach to update the doctest library directly to latest version, instead of patching the old library
https://github.com/Azure/azure-sdk-for-cpp/pull/4501

**Pull request merged**
