### PR TITLE
integrate TelemetryPolicy into Blob Service

### PR DESCRIPTION
**Pull request by JinmingHu-MSFT**

### CODE REVIEW

**Comment by katmsft** [comment]
Since we are releasing different libraries, should we follow .NET's folder structure in general?
Ref: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage
Each package has it's own `inc`, `src`, `sample` etc.

**Comment by JinmingHu-MSFT** [comment]
> Since we are releasing different libraries, should we follow .NET's folder structure in general?
> Ref: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage
> Each package has it's own `inc`, `src`, `sample` etc.

I don't know. I don't feel it's necessary though.

**Comment by katmsft** [comment]
> > Since we are releasing different libraries, should we follow .NET's folder structure in general?
> > Ref: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage
> > Each package has it's own `inc`, `src`, `sample` etc.
> 
> I don't know. I don't feel it's necessary though.

I think we should separate the folders for future Vcpkg releases. Can you please create an item to track as this is not going to fit into our private preview release?

**Comment by katmsft** [comment]
[Feature Request] Reconstruct the folder hierachy for Azure Storage. #339

**Pull request merged**
