### PR TITLE
add "Azure::Core::" prefix for Base64 functions in auto-generator and re-format code

### PR DESCRIPTION
**Pull request by Jinming-Hu**
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/master/CONTRIBUTING.md#pull-requests).

- [x] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [x] Doxygen docs
- [x] Unit tests
- [x] No unwanted commits/changes
- [x] Descriptive title/description
  - [x] PR is single purpose
  - [x] Related issue listed
- [x] Comments in source
- [x] No typos
- [x] Update changelog
- [x] Not work-in-progress
- [x] External references or docs updated
- [x] Self review of PR done
- [x] Any breaking changes?

closes https://github.com/Azure/azure-sdk-for-cpp/issues/1299

### CODE REVIEW

**Review by katmsft — APPROVED** [review]
Only seeing reformatting here.

**Comment by ahsonkhan** [comment]
> Only seeing reformatting here.

Same. I am assuming the PR description is referring only to the generator, since the generated code is identical.

**Comment by Jinming-Hu** [comment]
> > Only seeing reformatting here.
> 
> Same. I am assuming the PR description is referring only to the generator, since the generated code is identical.

yep

**Pull request merged**
