### PR TITLE
Added breaking change documentation for behavior change in Core.

### PR DESCRIPTION
**Pull request by katmsft**

### CODE REVIEW

**Comment by katmsft** [comment]
@vinjiang @Jinming-Hu 
This is the behavior breaking change that's Storage team did not catch, causing Storage's beta.3 release having a critical bug that needs to be hotfixed.

**Comment by vhvb1989** [comment]
The breaking change was documented on this PR: https://github.com/Azure/azure-sdk-for-cpp/pull/598

The main reason of that PR was to make URL class to get `all values` as url encoded.
Storage team fixed the AppendQueryParamenter() because the name of the function changed.
But ApendPath() was ignored.
Note how in that PR we even change the arg name for AppendPath to be 
`void AppendPath(const std::string& encodedPath)` so it was very clear that the value is expected to be encoded.

Core also exposed Encode/Decode APIs for Storage to call before adding values to a URL, however, Storage team has created their own Encoding functions.

**Comment by ahsonkhan** [comment]
This PR had a couple other API/behavioral changes: https://github.com/Azure/azure-sdk-for-cpp/pull/730

@vhvb1989, @RickWinter - should we enumerate all of them in the CL?

**Review by ahsonkhan — APPROVED** [review]

**Review by RickWinter — APPROVED** [review]

**Comment by Jinming-Hu** [comment]
> The breaking change was documented on this PR: #598
> 
> The main reason of that PR was to make URL class to get `all values` as url encoded.
> Storage team fixed the AppendQueryParamenter() because the name of the function changed.
> But ApendPath() was ignored.
> Note how in that PR we even change the arg name for AppendPath to be
> `void AppendPath(const std::string& encodedPath)` so it was very clear that the value is expected to be encoded.
> 
> Core also exposed Encode/Decode APIs for Storage to call before adding values to a URL, however, Storage team has created their own Encoding functions.

Well, I don't think you should rely on storage team reading every line of code in your PR. For these kind of breaking changes, it'll be better if you can explicitly notify us in some way.

**Pull request merged**
