### PR TITLE
add livetest regex

### PR DESCRIPTION
**Pull request by vhvb1989**
@LarryOsterman

### CODE REVIEW

**Review by LarryOsterman — APPROVED** [review]

**Review by ahsonkhan — APPROVED** [review]

**Comment by danieljurek** [comment]
This is happening because the pipeline was generated without the full set of variable groups. Future pipelines are fixed here: https://github.com/Azure/azure-sdk-for-cpp/pull/3353 ... I've also added the missing variable groups and will kick off another run.

**Comment by danieljurek** [comment]
I'm seeing a failure when deploying resources... Do we need to specify a region explicitly? 

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1372524&view=logs&j=0e119b68-c922-5ad7-2413-fa5b213ae9b8&t=b064c558-0b26-5a39-76cb-6e667dc889e4&l=1085

```
     | Message=The provided location 'westus2' is not available for
     | resource type 'Microsoft.Attestation/attestationProviders'.
```

**Comment by LarryOsterman** [comment]
> I'm seeing a failure when deploying resources... Do we need to specify a region explicitly?
> 
> https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1372524&view=logs&j=0e119b68-c922-5ad7-2413-fa5b213ae9b8&t=b064c558-0b26-5a39-76cb-6e667dc889e4&l=1085
> 
> ```
>      | Message=The provided location 'westus2' is not available for
>      | resource type 'Microsoft.Attestation/attestationProviders'.
> ```

The attestation service is not available in WestUS2. Use WestUS instead.

**Comment by vhvb1989** [comment]
covered by: https://github.com/Azure/azure-sdk-for-cpp/pull/3355/files

**Pull request closed without merging**
