### PR TITLE
Force a popup in the pipeline

### PR DESCRIPTION
**Pull request by LarryOsterman**
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Comment by RickWinter** [comment]
@danieljurek , @LarryOsterman Would be great to get this functionality into the pipelines.  What work remains to get this across the finish line?

**Comment by danieljurek** [comment]
If memory serves we weren't able to get a screenshot-able popup from this attempt.

**Comment by antkmsft** [comment]
@LarryOsterman did we get what we wanted from this PR? Can it be closed?

**Comment by LarryOsterman** [comment]
@danieljurek needs to chime in on this, but I think we decided it was a failure :(.

**Comment by danieljurek** [comment]
We did not observe popups in our screenshot: 

image

We can close this. Thanks for helping investigate, @LarryOsterman

**Pull request closed without merging**
