### PR TITLE
Merge main into feature/amqp

### PR DESCRIPTION
**Pull request by LarryOsterman**
# Merge main into feature/amqp

Verified that there are no merge issues - this PR has no changes different from those currently in main (with 1 minor change).

## Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Review by antkmsft — APPROVED** [review]
Why do you still need the branch?

**Comment by LarryOsterman** [comment]
> Why do you still need the branch?

Because George's EventHubs work is still based on this branch :(. I'm meeting with him today to discuss how we get eventhubs into main.

**Comment by antkmsft** [comment]
I see the CI is failing on coverage, reporting `0%`, which is not what I'd expect - you do have tests, I saw them.
Have you checked the `create_code_coverage()` cmake macro parameters, maybe that is why it is not picking up the right scope and finds it out as `0%`?
for example, you have the line, "`create_code_coverage(core azure-core-amqp azure-core-amqp-tests "tests?/*;samples?/*")`" - you have `tests` as plural, while the other libs have it as `test` (singular). Even though the regex should be capturing both `test` and `tests`, maybe it is actually not working as expected?

**Comment by LarryOsterman** [comment]
> I see the CI is failing on coverage, reporting `0%`, which is not what I'd expect - you do have tests, I saw them. Have you checked the `create_code_coverage()` cmake macro parameters, maybe that is why it is not picking up the right scope and finds it out as `0%`? for example, you have the line, "`create_code_coverage(core azure-core-amqp azure-core-amqp-tests "tests?/*;samples?/*")`" - you have `tests` as plural, while the other libs have it as `test` (singular). Even though the regex should be capturing both `test` and `tests`, maybe it is actually not working as expected?

AMQP's code coverage is at about 93%, higher than other parts of the tree. The test vs tests is a non-issue.

The probable reason for coverage failing is that there was a test failure. That's what it is 99% of the time. And since this codebase is 100% identical to main, it's probably a transient test failure.

**Comment by LarryOsterman** [comment]
> > I see the CI is failing on coverage, reporting `0%`, which is not what I'd expect - you do have tests, I saw them. Have you checked the `create_code_coverage()` cmake macro parameters, maybe that is why it is not picking up the right scope and finds it out as `0%`? for example, you have the line, "`create_code_coverage(core azure-core-amqp azure-core-amqp-tests "tests?/*;samples?/*")`" - you have `tests` as plural, while the other libs have it as `test` (singular). Even though the regex should be capturing both `test` and `tests`, maybe it is actually not working as expected?
> 
> AMQP's code coverage is at about 93%, higher than other parts of the tree. The test vs tests is a non-issue.
> 
> The probable reason for coverage failing is that there was a test failure. That's what it is 99% of the time. And since this codebase is 100% identical to main, it's probably a transient test failure.
> 
> That's not the root cause, I have no idea why the code coverage tooling decided that absolutely no tests were run (that's what 0% coverage means - there are no tests run at all).

Ok - coverage is working fine, the reporting is broken - working with Daniel to figure out why. Probably related to restarting a failed job.

**Pull request merged**
