### PR TITLE
Update the changelog wording and content for the upcoming release.

### PR DESCRIPTION
**Pull request by ahsonkhan**
**Left to do:**
Review the list of commits between the previous release and current master to make sure everything is covered.

https://github.com/Azure/azure-sdk-for-cpp/compare/1df5cfac9c038d33092f5ad765be92d18b65c63d...f8aebf5634ebccb37529d2255003bbd5cb358eb2

### CODE REVIEW

**Review by vhvb1989 — APPROVED** [review]

**Comment by vhvb1989** [comment]
> Review the list of commits between the previous release and current master

I think we should stop doing this task.  If it can be automated fine, if not, it is more time costly than the benefit of it.
At the end it is a duplicated effort if we were already been reviwing the changelog on every PR

**Comment by ahsonkhan** [comment]
> I think we should stop doing this task. If it can be automated fine, if not, it is more time costly than the benefit of it.
At the end it is a duplicated effort if we were already been reviwing the changelog on every PR

In the ideal case, I agree with you. This is more about doing due diligence to make sure things aren't missed. Do you have a better solution?

- We need to add that `AuthenticationException` was changed. It no longer derives from `runtime_error` but rather `exception`, from https://github.com/Azure/azure-sdk-for-cpp/pull/1222. @antkmsft

**Comment by ahsonkhan** [comment]
@antkmsft should we add a point about `vcpkg` support as package distribution from https://github.com/Azure/azure-sdk-for-cpp/pull/1013 under "Other changes"?

**Comment by antkmsft** [comment]
@ahsonkhan I would not mention VcPkg, but I am not against it either.
Regarding the DateTime changes, I like the set of bullet points that came with my PR.

**Comment by ahsonkhan** [comment]
> Regarding the DateTime changes, I like the set of bullet points that came with my PR.

@antkmsft, quite a few things changed that aren't mentioned in the CL:
https://www.diffchecker.com/uR4YiNXD

For example, the fact that `DateTime` is now a type that derives from `public Details::Clock::time_point`.

Here's what we have currently, which doesn't cover everything:
- Added default constructor to `DateTime`.
- Added `DateTime` supporting dates since 0001.

- Removed `DateTime::operator Duration()`.
- Removed `DateTime::Now()`.

What about removing `typedef std::chrono::duration<int64_t, std::ratio<1, 10000000>> Duration;` We also removed the +/- math operators on DateTime, along with changed the comparison operators to now accept `std::chrono::system_clock::time_point`

**Comment by antkmsft** [comment]
@ahsonkhan DateTime still supports `+=` operator, we just inherit it. Syntax is the same.
I don't think we should mention that we inherit from something in the Details namespace.
Let's mention the improved interoperability with std::chrono::system_clock.
We always threw invalid_argument, but it was documented incorrectly.
Yes, duration typedef was removed.
So, I would put it like this:
```
#New Features
Added interoperability between `std::chrono::system_clock` types and DateTime.

#Breaking Changes
Removed DateTime::Duration typedef.

#Bug fixes
Fixed DateTime documentation to reference the correct type of exception being thrown.
```

**Comment by ahsonkhan** [comment]
> I don't think we should mention that we inherit from something in the Details namespace.

I didn't even notice that was in `Details`. That's strange. Aren't we exposing something publicly this way that is "private"? Why is `time_point` in `Details`?

**Comment by vhvb1989** [comment]
> Here's a list of things we need to update in the CL that were missed:

Are you planning to update this PR and the list of changes you mention to the CL?  
This PR is currently the only PR blocking the release

**Comment by vhvb1989** [comment]
Merge this PR to add the missing changes to CL mentioned by @ahsonkhan in a new PR

**Comment by ahsonkhan** [comment]
> This PR is currently the only PR blocking the release

Also waiting on https://github.com/Azure/azure-sdk-for-cpp/pull/1283

**Comment by ahsonkhan** [comment]
> (for storage): #981

FYI @katmsft and @Jinming-Hu can you please go  through the PRs and changes between the previous release of storage and now to capture any missing Changelog updates?

For example, please add the bug fix from https://github.com/Azure/azure-sdk-for-cpp/pull/981.

Here are the commits:
https://github.com/Azure/azure-sdk-for-cpp/compare/a96f4c6f7dcacb6f7bf4ccab7ea9f04e980fdd95...21ed9e3376f44d91b914c28518812f7053a25f54

**Pull request merged**
