### PR TITLE
Renamed dockerfiles in an attempt to make CG happy

### LINKED ISSUE #4962: CI has warnings around docker images used for squid proxy from an external registry
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3091974&view=logs&j=5f3ffd68-137a-5778-3aee-fd1fc601ce2c&t=92d57749-67c2-5138-77c7-1a752168f73b&l=28

Reference link: https://eng.ms/docs/more/containers-secure-supply-chain

```text
> Starting DockerFile Analysis:
##[warning]sdk/core/azure-core/test/ut/proxy_tests/localproxy.passwd/Dockerfile - Container usage from external registry 'docker.io' found.
##[warning]sdk/core/azure-core/test/ut/proxy_tests/localproxy/Dockerfile - Container usage from external registry 'docker.io' found.
##[warning]sdk/core/azure-core/test/ut/proxy_tests/remoteproxy.passwd/Dockerfile - Container usage from external registry 'docker.io' found.
##[warning]sdk/core/azure-core/test/ut/proxy_tests/remoteproxy/Dockerfile - Container usage from external registry 'docker.io' found.
> Starting Pipeline Configuration Security Analysis:
Azure Artifacts Configuration Analysis found 1 NPM package configuration file in the repository which do not comply with Microsoft package feed security policies. The specific problems are listed above. Please visit https://aka.ms/cfs for more details. If you need additional help, email (feedprotection@microsoft.com).
##[warning]Container security analysis found 4 violations. This repo has one or more docker files having references to images from external registries. Please review https://aka.ms/containers-security-guidance to remove the reference of container images from external registries. Please reach out via teams (https://aka.ms/cssc-teams) or email (cssc@microsoft.com) for any questions or clarifications.
Finishing: Secure Supply Chain Analysis (auto-injected by policy)
```

Here is an example of the Docker file:
https://github.com/Azure/azure-sdk-for-cpp/blob/f04b7164eb054d1b94018f42e2cf47fc33980a6a/sdk/core/azure-core/test/ut/proxy_tests/localproxy/Dockerfile#L5

### PR DESCRIPTION
**Pull request by LarryOsterman**
Fixes #4962 

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Review by antkmsft — APPROVED** [review]

**Comment by LarryOsterman** [comment]
Ok. This one appears to work correctly.

**Comment by RickWinter** [comment]
@danieljurek What's the recommend way to handle Docker files in the repo?

**Comment by danieljurek** [comment]
If we're not using the container and we don't care if customers use it then we can just put [a comment](https://eng.ms/docs/initiatives/open-source-at-microsoft/tools/nuget_security_analysis/container_registry_analysis#can-i-disable-this-check) at the top of the file like: 

```dockerfile
# DisableDockerDetector "This was used for testing in the past. If such testing can be supported in the future this container will be used again."
```


If customers won't be using this container but we want to use the container we can migrate the container to an ACR instance hosted by EngSys, similar to [how we did it for C](https://github.com/Azure/azure-sdk-for-c/blob/feature/v2/eng/scripts/Setup-MQTTContainer.ps1#L9C32-L9C32). Since use of these containers isn't well supported in our CI system I don't see value in moving these containers over just yet. If that changes, we should move them over.

**Pull request closed without merging**
