### PR TITLE
Azure-Core: If no timezone information is present in string, assume local time and convert to UTC

### PR DESCRIPTION
**Pull request by janbernloehr**
This PR proposes a fix for #5075. There might be side-effects, though. Feedback welcome.

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [x] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [x] No unwanted commits/changes
- [x] Descriptive title/description
  - [x] PR is single purpose
  - [x] Related issue listed
- [x] Comments in source
- [x] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [x] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Review by antkmsft — CHANGES_REQUESTED** [review]
Thank you, @janbernloehr!
This behavior existed since the beginning, and it is hard to tell right away, how, if, and where it would affect us.
This looks like a breaking change - previously a user would parse `2023-10-26T18:18:18` and get UTC value, now they'll get a different value.

FWIW, format behavior is consistent with .NET:
```cs
Console.WriteLine(DateTime.Parse("2023-10-26T18:18:18").ToLocalTime()); // When ran in PST time zone, prints "Oct 26, 2023 11:18:18".
```

I think #5075 should be fixed tactically in the Azure CLI credential - it could be that `DateTime::Parse()` gets something like a `treatNoTimeZoneAsLocal = false` third parameter, or something like that. And then the AzureCLI credential passes that flag to the `TokenCredentialImpl`, and then its token parser uses that flag when parsing the token expiration time.

cc @ahsonkhan

**Comment by LarryOsterman** [comment]
One minor note: [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339#section-5.6) requires a timezone element.

Our parser appears to allow RFC 3339 elements without a timezone element, but it is a non-standard extension. We certainly should never generate such a time.

**Comment by janbernloehr** [comment]
> One minor note: [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339#section-5.6) requires a timezone element.
> 
> Our parser appears to allow RFC 3339 elements without a timezone element, but it is a non-standard extension. We certainly should never generate such a time.

It could probably also be fixed in az cli by creating a string complying with RFC 3339

**Comment by antkmsft** [comment]
Thank you, @janbernloehr - these are great links and the context, I even left one possible idea in the first one.
But I don't think this SDK will be able to enjoy that feature they may add in the future version, because our customer may have the old version of Azure CLI extended, and for that, we will need to not be using any new command line switches added in the older versions, and instead we would need to be treating an RFC3339 timestamp without `Z` or `+NNNN` in the end as local time, but only when parsing the token expiration from  `az account get-access-token` output, and not in any other scope.

**Comment by jiasli** [comment]
Hi @janbernloehr, @antkmsft, I am the owner of Azure CLI command `az account get-access-token`. Returning `expiresOn` as a local datetime is only a legacy from the ADAL age. We would not make any change on that field.

`az account get-access-token` will start returning `expires_on` as a POSIX timestamp since the next release, and we would highly recommend using that new field as it is timezone-irrelevant and consistent across various tools and services - MSAL, Azure SDKs, Managed Identity.

**Comment by antkmsft** [comment]
Thank you @jiasli - the Azure SDK for C++'s current implementation would successfully be able to parse Unix timestamp (https://github.com/Azure/azure-sdk-for-cpp/blob/50c18516df110058e1faac27b38360bc56db7c6e/sdk/identity/azure-identity/src/token_credential_impl.cpp#L292-L327), should it replace the RFC3339 string, no code change is needed.

AzureSDK for .NET would break - https://github.com/Azure/azure-sdk-for-net/blob/ba1e6df24131bfc88619c12c4c592933f78fcd18/sdk/identity/Azure.Identity/src/Credentials/AzureCliCredential.cs#L236, we should communicate this to them. Possibly, some other SDKs may get broken by this change as well.

cc @ahsonkhan @schaabs @scottaddie @azure-sdk-write-identity

**Comment by scottaddie** [comment]
@jiasli Which version number will contain this new `expires_on` field?

**Comment by jiasli** [comment]
> @jiasli Which version number will contain this new `expires_on` field?

@scottaddie, I have updated my comment https://github.com/Azure/azure-sdk-for-cpp/pull/5076#issuecomment-1784680918 to include that information.

**Comment by jiasli** [comment]
@antkmsft, I provided more information in https://github.com/Azure/azure-cli/pull/27476. We are not going to make any change on `expiresOn`, so it won't breaking any existing SDKs.

**Comment by antkmsft** [comment]
#5179 would treat datetimes it gets from azcli as local time, if no time zone information is present.

**Comment by antkmsft** [comment]
Fixed in #5179

**Pull request closed without merging**
