### PR TITLE
Storage January release

### PR DESCRIPTION
**Pull request by microzchang**
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Review by antkmsft — APPROVED** [review]
@microzchang, please run Prepare-Release.ps1 for these 3 releases. It will create a work item for the corresponding query, which will be used early tomorrow.

(Single Changelog and package_version.hpp update PR is not enough - Prepare-Release.ps1 also needs to be run by 1/4 EOD (Redmond time), but factually this time 10AM on 1/5 Redmond time is the latest).

cc @gearama

**Comment by microzchang** [comment]
> @microzchang, please run Prepare-Release.ps1 for these 3 releases. It will create a work item for the corresponding query, which will be used early tomorrow.
> 
> (Single Changelog and package_version.hpp update PR is not enough - Prepare-Release.ps1 also needs to be run by 1/4 EOD (Redmond time), but factually this time 10AM on 1/5 Redmond time is the latest).
> 
> cc @gearama

@antkmsft  Thanks for your reminder. I have created work items for these 3 releases right now.

**Review by Jinming-Hu — APPROVED** [review]

**Pull request merged**
