### PR TITLE
Fixed datalake/file service protocol layer remaining issues.

### PR DESCRIPTION
**Pull request by katmsft**
Fixes https://github.com/Azure/azure-sdk-for-cpp/issues/435

### CODE REVIEW

**Review by JinmingHu-MSFT — APPROVED** [review]

**Comment by katmsft** [comment]
Fixes https://github.com/Azure/azure-sdk-for-cpp/issues/434

**Comment by katmsft** [comment]
Fixes https://github.com/Azure/azure-sdk-for-cpp/issues/383.

**Comment by katmsft** [comment]
Fixes https://github.com/Azure/azure-sdk-for-cpp/issues/392

**Review by JinmingHu-MSFT — APPROVED** [review]

**Review by JinmingHu-MSFT — CHANGES_REQUESTED** [review]
ACL, API, URL, HTTPGetterInfo,

**Review by JinmingHu-MSFT — APPROVED** [review]

**Pull request merged**
