### PR TITLE
Add conditional request support

### PR DESCRIPTION
**Pull request by RickWinter**
- MatchConditions
- RequestConditions

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/master/CONTRIBUTING.md#pull-requests).

- [x] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [x] Doxygen docs
- [x] Unit tests
- [x] No unwanted commits/changes
- [x] Descriptive title/description
  - [x] PR is single purpose
  - [x] Related issue listed
- [x] Comments in source
- [x] No typos
- [x] Update changelog
- [x] Not work-in-progress
- [x] External references or docs updated
- [x] Self review of PR done
- [x] Any breaking changes?

### CODE REVIEW

**Review by ahsonkhan — APPROVED** [review]

**Comment by ahsonkhan** [comment]
Fixes https://github.com/Azure/azure-sdk-for-cpp/issues/1138 and https://github.com/Azure/azure-sdk-for-cpp/issues/1157, but presumably storage needs to start consuming it as well.
cc @Jinming-Hu, @katmsft

**Comment by RickWinter** [comment]
@ahsonkhan In the other PR you asked about where this would be used.  Storage uses it in some of their types.  They would be set on the request object headers by the client if the values are supplied.  Validation of if the values work as expected is primarily up to the service.  Our (Azure::Core) is only responsible for sending the k/v pair <string:string> as a header.

**Review by ahsonkhan — CHANGES_REQUESTED** [review]
Hold off on merging this until storage is done with their release of files shares, beta.7.

**Review by ahsonkhan — APPROVED** [review]
Never mind, this shouldn't have any impact on future releases, especially since this PR is purely feature addition (and no one is calling it yet).

**Review by antkmsft — APPROVED** [review]

**Pull request merged**
