### PR TITLE
Always release to vcpkg when doing Daily Release

### PR DESCRIPTION
**Pull request by danieljurek**

### CODE REVIEW

**Review by antkmsft — APPROVED** [review]

**Review by antkmsft — COMMENTED** [review]
I understand this is a work in progress, but I approve and by that I mean that I like the intent of this change and I trust that you will verify that the fix does what you intend before you check in. I may return to re-review as you have more pushes, but in general I don't want to block you if you are ready.

**Comment by antkmsft** [comment]
I took the daily verification branch, manually merged all changes from `vcpkg/master`, and then applied all changes as if automation was working correctly all this time, so now it is up to date for all 13 of our packages. Everything passes. If the problem was caused by a mixed state of changes, maybe this will let it fix by itself.
https://github.com/microsoft/vcpkg/pull/17119

**Comment by antkmsft** [comment]
So, the vcpkg PR was looking perfect, and the the daily run happened, and it replaced what's been there with a single commit for opentelemetry - https://github.com/microsoft/vcpkg/pull/17119/files. So, the problem was not fixed by me simply pushing all the right commits at one point.

**Comment by antkmsft** [comment]
We'd still need this fix- the daily runs do not include all the packages.

**Comment by danieljurek** [comment]
https://github.com/microsoft/vcpkg/compare/master...azure-sdk:vcpkg:djurek/verify-4334?expand=1 -- Testing with the pipelines

**Review by antkmsft — APPROVED** [review]

**Comment by danieljurek** [comment]
Overriding check-enforcer, the failures are not relevant and testing was done in a manner other than using checks.

**Comment by danieljurek** [comment]
The checks API appears to be pretty far behind on this PR. Closing and re-opening.

**Pull request merged**
