### PR TITLE
Add "Blob" before every "Container"

### PR DESCRIPTION
**Pull request by Jinming-Hu**

### CODE REVIEW

**Review by vhvb1989 — APPROVED** [review]
Add a changelog entry for all the breaking changes here please

**Review by katmsft — APPROVED** [review]

**Comment by Jinming-Hu** [comment]
CI failed in DataLake [log](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/634286/logs/339), @katmsft can you take a look?

**Pull request merged**
