### PR TITLE
Remove custom logic in Curl Transport for keep alive to support HTTP responses below version 1.1 (and remove unnecessary public methods on RawResponse).

### PR DESCRIPTION
**Pull request by ahsonkhan**
Follow-up from https://github.com/Azure/azure-sdk-for-cpp/pull/5473

There is currently no customer scenario where they'd benefit from exposing the HTTP protocol version from the `RawResponse()`. 

Furthermore, there is no known scenario where a supported Azure service returns a response using HTTP version 1.0, so we do not need to complicate the curl transport HTTP Keep Alive logic any further to support the defaults from HTTP/1.0. Since that was the only user of those methods, removing them from `RawResponse`. When it comes to the HTTP request, we currently always specify HTTP 1.1 in the request line.

If a scenario comes up in the future, where we do need to support non-HTTP 1.1 protocol versions, we could update the `ResponseBufferParser` within the curl transport to capture the major/minor version of the protocol while parsing the response, instead of saving it and then later fetching it from the `RawResponse`. This way, we wouldn't need to add new public surface area to `RawResponse` that isn't intended for end customers.

cc @Jinming-Hu, @mchelnokov

### CODE REVIEW

**Comment by RickWinter** [comment]
It seems reasonable to expose the Http version returned from the server. Other languages do expose the HttpVersion and even go so far as allowing you to change the version sent. Here is the link to the [.NET impl](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultrequestversion?view=net-8.0)

**Comment by ahsonkhan** [comment]
> It seems reasonable to expose the Http version returned from the server.

Reasonable - maybe. Necessary - **no**. No harm in waiting until it becomes actually needed.

> Other languages do expose the HttpVersion and even go so far as allowing you to change the version sent

Like you said, the C++ **SDK** does not.

Recall, our philosophy from the get-go is to provide a networking stack for the needs of Azure services, **and not** a general purpose HTTP stack with all the bells and whistles. We don't add public surface area that isn't used or driven by a concrete service or customer scenario.

Supporting HTTP/1.0 is a non-scenario.

**Comment by RickWinter** [comment]
Exposing the HttpVersion is not making it general purpose. It's about adding support to allow the underlying transport to work as expected.

**Comment by ahsonkhan** [comment]
> It's about adding support to allow the underlying transport to work as expected.

It's not needed.

**Comment by RickWinter** [comment]
> > It's about adding support to allow the underlying transport to work as expected.
> 
> It's not needed.

Your change assumes the request goes directly to Azure. It might not, it might go across a proxy. Its legal for the proxy to do things to the request and that could involve altering the httpversion.

**Comment by ahsonkhan** [comment]
My change does nothing to the **request**.

**Comment by RickWinter** [comment]
> My change does nothing to the **request**.

Correct. It doesn't change the request. It assumes a request made with http 1.1 will return a http 1.1 response. It is not required for a server to return 1.1 and a proxy can affect this behavior. If a response comes back with http 1.0 we must handle the response appropriately.

**Comment by ahsonkhan** [comment]
Closing this in favor of https://github.com/Azure/azure-sdk-for-cpp/pull/5608

**Pull request closed without merging**
