### PR TITLE
Only check the touched markdown files in PR for the Verify link step

### PR DESCRIPTION
**Pull request by sima-zhu**
Java: https://github.com/Azure/azure-sdk-for-java/pull/16008
.NET: https://github.com/Azure/azure-sdk-for-net/pull/15929
Python: https://github.com/Azure/azure-sdk-for-python/pull/14466
JS: https://github.com/Azure/azure-sdk-for-js/pull/11803
Android: https://github.com/Azure/azure-sdk-for-android/pull/405
C: https://github.com/Azure/azure-sdk-for-c/pull/1431
CPP: https://github.com/Azure/azure-sdk-for-cpp/pull/787
Go: https://github.com/Azure/azure-sdk-for-go/pull/12809
IOS: https://github.com/Azure/azure-sdk-for-ios/pull/488

### CODE REVIEW

**Review by weshaggard — APPROVED** [review]

**Review by weshaggard — APPROVED** [review]

**Comment by ahsonkhan** [comment]
What's motivating this change? Was this causing problems somehow?

**Comment by sima-zhu** [comment]
> What's motivating this change? Was this causing problems somehow?

Most of the lang repo are lack of the ability to scan the root readme (markdown outside of sdk scope). So every time people add wrong link under root repo, only the nightly build aggregate-report can catch it. We want to minimize the two steps fix to one step.
Also, there is no need to scan the links if the PRs do not touch the markdown files.

**Comment by ahsonkhan** [comment]
> So every time people add wrong link under root repo, only the nightly build aggregate-report can catch it.

Why is that?

> We want to minimize the two steps fix to one step.

How does it minimize the number of steps? Do we still have the nightly build that verifies all the links? If not, don't we lose some coverage? 

If the repo _somehow_ is in a state that it contains invalid links, are we still going to be able to catch that somehow, regardless of this change?

**Comment by weshaggard** [comment]
@sima-zhu it doesn't look like the cpp repo has an aggregate-reports pipeline like other language repos so @ahsonkhan is correct that for cpp this will leave a gap because we will never check the links unless something is touching that MD file in a PR. So for languages where we don't have a nightly pipeline runs and checks all MD files, we should either add one or keep checking all MD files.

**Comment by sima-zhu** [comment]
@weshaggard @ahsonkhan  I am trying to check over if cpp have the ability to scan the root readme. However, it seems we cannot scan root readme for cpp as well. I think the best approach to address this is we add a nightly pipeline to check all links like other lang's aggregate-report.

**Comment by ahsonkhan** [comment]
Thanks @weshaggard, that makes sense. I would still like to understand the benefit/concern of this change for other languages who might have a nightly aggregate report.

**Comment by sima-zhu** [comment]
@ahsonkhan This is one of the readme we currently miss to scan against. https://github.com/Azure/azure-sdk-for-cpp/blob/master/README.md
Other langs have the same issue.

**Comment by sima-zhu** [comment]
ci.yml provides us which sdk directory (storage, core etc) to scan against. The link verification scripts scan the markdown files under sdk directory parameter. However, we do not have any ci.yml cover the path outside of sdk scope. That's why we have the miss.

**Comment by ahsonkhan** [comment]
Gotcha. Can we change (or add) the ci.yml script to include the root directory too or is there a reason why want to exclude them?

For instance, can we add something like `*`, here:
https://github.com/Azure/azure-sdk-for-cpp/blob/12b7a5e449c588afaa2a1c094a618e83240ea4de/sdk/core/ci.yml#L11-L14

**Comment by weshaggard** [comment]
Unfortunately devops doesn't really have support wildcards (https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#wildcards) for paths so if we added the root of the repo as a trigger I think it would trigger for every change in the repo, not just the files in the root. So I'm not sure we want to do that and we don't do it in any of the other languages today either.

We could however have one or all the pipelines in the cpp repo check all MD files in the repo that change but it would require that they get triggered by other changes or manually triggered to check them which is what this change is about.

I think perhaps the best option is to keep this change add to add another nightly aggregate-reports pipeline, like all other languages, that runs and will always check all MD files for broken links.

**Comment by ahsonkhan** [comment]
> I think perhaps the best option is to keep this change add to add another nightly aggregate-reports pipeline, like all other languages, that runs and will always check all MD files for broken links.

👍

**Comment by sima-zhu** [comment]
The aggregate-report pipeline has to setup for all necessary checking against entire repo. It should take more things into consideration besides of link verification. We currently plan to scan the entire repo in yml file, which is able to cover all md files for the very first step. If it takes too much time for scanning, we will switch to another plan. Will close the PR and open another one for covering root readme

**Pull request closed without merging**
