### PR TITLE
changelog for release Core Beta 5 and Identity Beta 3

### PR DESCRIPTION
**Pull request by vhvb1989**
PR for releasing:
- Core beta 5
- Identity beta 3

### CODE REVIEW

**Comment by vhvb1989** [comment]
CI run: https://dev.azure.com/azure-sdk/public/_build/results?buildId=716108&view=results

**Comment by ahsonkhan** [comment]
List of commits for our changelog since the previous release:
https://github.com/Azure/azure-sdk-for-cpp/compare/af097c8e65d792387e61aca4a069efe47b6d71e5...06d66492ebb741e30731e4e85195f0b5ba0dc10b

@mitchdenny, @danieljurek - the azure devops pipeline results aren't showing up in GitHub for CI in our PRs. Is this a known issue?
cc @weshaggard

**Review by ahsonkhan — APPROVED** [review]
Give me a few minutes to go through the list of commits to verify we captured everything.

**Review by RickWinter — APPROVED** [review]

**Comment by ahsonkhan** [comment]
Here are three bug fixes we want changelog entries for:
https://github.com/Azure/azure-sdk-for-cpp/pull/1346 - Fix link errors when producing a DLL and add UWP compilation support
https://github.com/Azure/azure-sdk-for-cpp/pull/1495 - Do not pass a placeholder user-agent string as a fallback when using WinHttp
https://github.com/Azure/azure-sdk-for-cpp/pull/1560 - Initialize local variables in implementation to fix warning within release builds on Linux.

**Comment by danieljurek** [comment]
> List of commits for our changelog since the previous release:
> [af097c8...06d6649](https://github.com/Azure/azure-sdk-for-cpp/compare/af097c8e65d792387e61aca4a069efe47b6d71e5...06d66492ebb741e30731e4e85195f0b5ba0dc10b)
> 
> @mitchdenny Mitch Denny FTE, @danieljurek Daniel Jurek FTE - the azure devops pipeline results aren't showing up in GitHub for CI in our PRs. Is this a known issue?
> cc @weshaggard Wes Haggard FTE

We are aware of an incident degrading pipeline availability earlier today. They may have some issues communicating build statues to GitHub. The builds did kick off. Most recent: 

* https://dev.azure.com/azure-sdk/public/_build/results?buildId=716108&view=results
* https://dev.azure.com/azure-sdk/public/_build/results?buildId=716112&view=results

**Comment by vhvb1989** [comment]
> Fix link errors when producing a DLL and add UWP compilation support
> #1495 - Do not pass a placeholder user-agent string as a fallback when using WinHttp
> #1560 - Initialize local variables in implementation to fix warning within release builds on Linux.

Done

**Pull request merged**
