### PR TITLE
Disable Mac build to unblock CI

### PR DESCRIPTION
**Pull request by antkmsft**

### CODE REVIEW

**Review by gearama — CHANGES_REQUESTED** [review]
i'm not sure we should do this, while the pipelines are blocked, we shouldn't reduce our coverage just to get it passed, at the end of the day we shoiuld get it fixes, irrelevant of how many things are blocked, merging without validation on mac is risky, several times i got breaks on mac that were not showing up on linux or windows

**Comment by gearama** [comment]
attestation and eventhubs will fail

**Comment by antkmsft** [comment]
@gearama , attestation and eventhubs will fail due to auth issues with samples which is fixed in other PR, but wich can't get checked in because of Mac issue?

See, this is not a permanent fix. But we need to somehow get unblocked. For example, there is also a PR that would give us better logs for vcpkg, but none can go in at the moment.

I'd say, we temporarily drop building on macs in our CI, but our commits get unblocked, and we are able to gather more information, because the root cause is very likely not within our repo.
As of releases, we are still covered by https://github.com/microsoft/vcpkg/pull/34835 as build validation for macs.

**Comment by weshaggard** [comment]
While the checks are failing you can still override check-enforcer after verifying they are the known issues and then merge the PR still.

**Comment by antkmsft** [comment]
Yes, we can merge to main, but we won't be able to release with pipelines failing

**Comment by gearama** [comment]
> @gearama , attestation and eventhubs will fail due to auth issues with samples which is fixed in other PR, but wich can't get checked in because of Mac issue?
> 
> See, this is not a permanent fix. But we need to somehow get unblocked. For example, there is also a PR that would give us better logs for vcpkg, but none can go in at the moment.
> 
> I'd say, we temporarily drop building on macs in our CI, but our commits get unblocked, and we are able to gather more information, because the root cause is very likely not within our repo. As of releases, we are still covered by [microsoft/vcpkg#34835](https://github.com/microsoft/vcpkg/pull/34835) as build validation for macs.

If rick approves that's fine by me, i want another set of eyes on this and to not be forgotten

**Comment by antkmsft** [comment]
There will be a proper fix tomorrow.

**Pull request closed without merging**
