### PR TITLE
Remove outdated link to the non-existing wiki from the contributing guide

### PR DESCRIPTION
**Pull request by ahsonkhan**

### CODE REVIEW

**Review by antkmsft — APPROVED** [review]
Approving per your request. Do not merge this - at least not with referencing C (not C++) SDK.

**Review by vhvb1989 — CHANGES_REQUESTED** [review]
aaaaaaa

**Comment by ahsonkhan** [comment]
> Do not merge this - at least not with referencing C (not C++) SDK.

The link was pointing to the C SDK and was wrong. We don't have a C++ wiki, so its fine to remove this line for now.

**Review by vhvb1989 — APPROVED** [review]

**Pull request merged**
