### PR TITLE
Add back package versions to the FolderList.cmake and remove EventHubs from the list for now

### PR DESCRIPTION
**Pull request by ahsonkhan**
Essentially, reverting the change from https://github.com/Azure/azure-sdk-for-cpp/pull/4755#discussion_r1268798025 since it broke CI and blocking PRs like:
https://github.com/Azure/azure-sdk-for-cpp/pull/4809

Fixes https://github.com/Azure/azure-sdk-for-cpp/issues/4810

### CODE REVIEW

**Review by LarryOsterman — CHANGES_REQUESTED** [review]
Please put eventhubs back on the list.

As long as this file exists, all the packages we support should be on the list.

**Comment by ahsonkhan** [comment]
What can I put as the versions for its dependencies, like azure-core-amqp?

**Comment by LarryOsterman** [comment]
> What can I put as the versions for its dependencies, like azure-core-amqp?

The current published version of azure-core-amqp seems like a reasonable version number for AMQP - that would be 1.0.0-beta.1, I believe.

**Review by LarryOsterman — APPROVED** [review]

**Review by antkmsft — COMMENTED** [review]
Let's have `"LATEST"` - https://github.com/Azure/azure-sdk-for-cpp/pull/4814#issue-1813131636

**Pull request merged**
