### PR TITLE
Guard against Windows' min/max macros

### PR DESCRIPTION
**Pull request by antkmsft**
Without this, we can't bring vcpkg baseline up to date (#5347).

It looks like one of our upstream dependencies ended up including `windows.h` without `#define NOMINMAX`, which absolutely can happen at any time - even without an upstream dependency, customer's code can have that include.

And I went and updated all our code to guard it against min/max macro expansion.
We do already some places guarded, but over all this time, we forgot about this, and added instances of it without the `()`. I updated all the instances.
I also added `#define NOMINMAX` and `#define WIN32_LEAN_AND_MEAN` to all the places, where we `#include <Windows.h>`. Most such places in the SDK code do define them already.

From https://dev.azure.com/azure-sdk/public/_build/results?buildId=3489702&view=logs&j=97f19394-1a2e-56f4-6b20-b9674826b151&t=1eb8b588-040a-5ab0-2acf-c712a2c821f7:

```
D:\a\_work\1\s\sdk\core\azure-core-test\inc\azure/core/test/test_proxy_manager.hpp(43,41): error C2220: the following warning is treated as an error [D:\a\_work\1\s\build\sdk\core\azure-core-tracing-opentelemetry\test\ut\azure-core-tracing-opentelemetry-test.vcxproj]
D:\a\_work\1\s\sdk\core\azure-core-test\inc\azure/core/test/test_proxy_manager.hpp(43,41): warning C4003: not enough arguments for function-like macro invocation 'max' [D:\a\_work\1\s\build\sdk\core\azure-core-tracing-opentelemetry\test\ut\azure-core-tracing-opentelemetry-test.vcxproj]
D:\a\_work\1\s\sdk\core\azure-core-test\inc\azure/core/test/test_proxy_manager.hpp(47,43): warning C4003: not enough arguments for function-like macro invocation 'min' [D:\a\_work\1\s\build\sdk\core\azure-core-tracing-opentelemetry\test\ut\azure-core-tracing-opentelemetry-test.vcxproj]
D:\a\_work\1\s\sdk\core\azure-core-test\inc\azure/core/test/test_proxy_manager.hpp(43,41): error C2589: '(': illegal token on right side of '::' [D:\a\_work\1\s\build\sdk\core\azure-core-tracing-opentelemetry\test\ut\azure-core-tracing-opentelemetry-test.vcxproj]
D:\a\_work\1\s\sdk\core\azure-core-test\inc\azure/core/test/test_proxy_manager.hpp(43): error C2062: type 'unknown-type' unexpected [D:\a\_work\1\s\build\sdk\core\azure-core-tracing-opentelemetry\test\ut\azure-core-tracing-opentelemetry-test.vcxproj]
```

### CODE REVIEW

**Comment by LarryOsterman** [comment]
I'm confused. How does wrapping uses of `min` and `max` in parentheses block the preprocessor from expanding the macro?

**Comment by Jinming-Hu** [comment]
> It looks like one of our upstream dependencies ended up including windows.h without #define NOMINMAX

Is it possible to find out which exactly dependency introduces `Windows.h`, add `#define NOMINMAX` before including the dependency header? Would it be an easier way to fix the issue?


> I'm confused. How does wrapping uses of min and max in parentheses block the preprocessor from expanding the macro?

I guess that's how C++ preprocessor works.
Function like macro only applies to those without parentheses around them

**Comment by antkmsft** [comment]
@LarryOsterman, enclosing in braces does prevent from macro expansion. See https://godbolt.org/z/MPWT5ndKz

**Comment by antkmsft** [comment]
@Jinming-Hu, it is possible to figure out, but I wouldn't do it - it is more fragile - what if the other dependency defines it?
What if a customer has
```cpp
#include <windows.h>
#include <azure/...> // too late to define NOMINMAX
```

Enclosing `min` and `max` in braces is universal, it works, it prevents from all possible combinations, future-proofs the code. Many libraries are doing it. We also were doing it before, we just stopped - https://github.com/Azure/azure-sdk-for-cpp/pull/1719

**Comment by LarryOsterman** [comment]
> @LarryOsterman, enclosing in braces does prevent from macro expansion. See https://godbolt.org/z/MPWT5ndKz

Wow. That works because the `()` characters disable the [preprocessor handling of function-like macros](https://en.cppreference.com/w/cpp/preprocessor/replace) - basically the `)` means that the preprocessor cannot match against `min()`.

**Comment by antkmsft** [comment]
@LarryOsterman, I think it is documented - 16.3.10 [of the Standard](https://github.com/cplusplus/draft/blob/main/papers/n4140.pdf) says

A preprocessing directive of the form
`#` `define` `identifier` `lparen` `identifier-list`<sub>`opt`</sub>`)` `replacement-list` `new-line`
`#` `define` `identifier` `lparen` `...` `)` `replacement-list` `new-line`
`#` `define` `identifier` `lparen` `identifier-list` `,` `...` `)` `replacement-list` `new-line`

defines a function-like macro with parameters, whose use is similar syntactically to a function call. The
parameters are specified by the optional list of identifiers, whose scope extends from their declaration in the
identifier list until the new-line character that terminates the #define preprocessing directive. Each subsequent instance of the function-like macro name **followed by a ( as the next preprocessing token** introduces
the sequence of preprocessing tokens that is replaced by the replacement list in the definition (an invocation
of the macro). The replaced sequence of preprocessing tokens is terminated by the matching ) preprocessing
token, skipping intervening matched pairs of left and right parenthesis preprocessing tokens. Within the
sequence of preprocessing tokens making up an invocation of a function-like macro, new-line is considered a
normal white-space character.

**Review by LarryOsterman — APPROVED** [review]

**Pull request merged**
