### PR TITLE
Move MHSM to region with more availability

### LINKED ISSUE #4613: Move Managed HSM testing to regions with more capacity
We should try these regions: Australia East, Brazil South, France Central, Japan West. Specifically, those which might be closer like France Central. My concern is about potential timeouts, so maybe we need to increase the timeouts for test runs against MHSMs.

/cc @pallavit @vcolin7

### PR DESCRIPTION
**Pull request by heaths**
Resolves #4613

### CODE REVIEW

**Review by gearama — APPROVED** [review]

**Comment by heaths** [comment]
@gearama your `GetRandomBytes` test has been failing for a while. Seems it either needs to be conditioned on whether a MHSM was provisioned (I use the existence of the output variable set as an env var for C#) or use a recording for CIs at least. But live tests will still need to be conditioned.

**Comment by gearama** [comment]
> @gearama your `GetRandomBytes` test has been failing for a while. Seems it either needs to be conditioned on whether a MHSM was provisioned (I use the existence of the output variable set as an env var for C#) or use a recording for CIs at least. But live tests will still need to be conditioned.

Actually there is anothe rproblem regarding the test proxy and winhttp , working on a fix

**Comment by heaths** [comment]
> @heaths Actually there is anothe rproblem regarding the test proxy and winhttp , working on a fix

Do you just want to amend this PR so that the CIs pass and we can merge cleanly?

**Review by vcolin7 — APPROVED** [review]

**Comment by antkmsft** [comment]
CI should be fixed once #5129 is merged.

**Review by vcolin7 — APPROVED** [review]

**Pull request merged**
