### PR TITLE
Update storage changelog to be consistent on section order, use past tense, and make it a bit more brief.

### PR DESCRIPTION
**Pull request by ahsonkhan**
Also fixes a couple of typos and added back-ticks that were missing.

### CODE REVIEW

**Comment by ahsonkhan** [comment]
Entry missing for:
https://github.com/Azure/azure-sdk-for-cpp/pull/1000#discussion_r557160916

**Review by Jinming-Hu — APPROVED** [review]

**Review by Jinming-Hu — APPROVED** [review]

**Comment by ahsonkhan** [comment]
@katmsft, waiting for your approval.

Looks like we already shipped, so we should probably update the release contents with these CL changes, once this PR is merged.

**Comment by ahsonkhan** [comment]
@msftbot do not merge unless @katmsft approves.

**Review by katmsft — APPROVED** [review]

**Comment by katmsft** [comment]
Did we actually agree to have past tense being the only valid form of change description? I mean I personally prefer this form but I remember that the conclusion for the design meeting is to use your own preferred form.

**Comment by katmsft** [comment]
Also, thanks for the prove-reading! @ahsonkhan

**Comment by ahsonkhan** [comment]
> Did we actually agree to have past tense being the only valid form of change description? I mean I personally prefer this form but I remember that the conclusion from the design meeting is to use your own preferred form.

No. However, while reading, it felt strange to have things in present tense (it made it seem like instructions to the user to do - Add new API X) and the fact that the tense was changing within a particular changelog section in some cases wasn't ideal.

**Pull request merged**
