### PR TITLE
Rename Get{Block/Append/Page}BlobClient -> As{Block/Append/Page}BlobC…

### PR DESCRIPTION
**Pull request by Jinming-Hu**
…lient

### CODE REVIEW

**Comment by Jinming-Hu** [comment]
@vhvb1989 code coverage tool causes CI to fail, can you take a look?

**Comment by Jinming-Hu** [comment]
@vhvb1989 code coverage tool causes CI to fail, can you take a look?

**Comment by vhvb1989** [comment]
Well, when you did `/azp run` you asked for all pipelines to be run (not only storage).
There is actually a bug for the live test code cov generation for core and template project, I will fix that, but it should not block you for this PR (not Storage Live test passed)

**Review by vhvb1989 — APPROVED** [review]

**Pull request merged**
