### PR TITLE
Renamed MaxResult/Segment to be PageSizeHint/SinglePage

### PR DESCRIPTION
**Pull request by katmsft**
Resolves https://github.com/Azure/azure-sdk-for-cpp/issues/1190

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/master/CONTRIBUTING.md#pull-requests).

- [x] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [x] Doxygen docs
- [x] Unit tests
- [x] No unwanted commits/changes
- [x] Descriptive title/description
  - [x] PR is single purpose
  - [x] Related issue listed
- [x] Comments in source
- [x] No typos
- [x] Update changelog
- [x] Not work-in-progress
- [x] External references or docs updated
- [x] Self review of PR done
- [x] Any breaking changes?

### CODE REVIEW

**Review by Jinming-Hu — APPROVED** [review]
How about set acl recursive?

**Comment by katmsft** [comment]
> How about set acl recursive?

Let's raise this in tomorrow's review meeting.

**Comment by katmsft** [comment]
Failing on known issue for ContainerAcl:
```
117: [ RUN      ] BlobContainerClientTest.AccessConditionLastModifiedTime
117: D:\a\1\s\sdk\storage\azure-storage-blobs\test\blob_container_client_test.cpp(673): error: Expected: containerClient.SetAccessPolicy(options) doesn't throw an exception.
117:   Actual: it throws.
117: D:\a\1\s\sdk\storage\azure-storage-blobs\test\blob_container_client_test.cpp(673): error: Expected: containerClient.SetAccessPolicy(options) doesn't throw an exception.
117:   Actual: it throws.
```

**Pull request merged**
