### PR TITLE
Added ARM template for Storage.

### PR DESCRIPTION
**Pull request by katmsft**

### CODE REVIEW

**Comment by Jinming-Hu** [comment]
what is this file used for?

**Comment by katmsft** [comment]
It's used for private CIs to generate Storage related credentials.

**Comment by Jinming-Hu** [comment]
> It's used for private CIs to generate Storage related credentials.

Is it able to work standalone? If not, I don't want to merge such a PR.

**Review by RickWinter — CHANGES_REQUESTED** [review]
This is a test only resource. It should be in the tests folder.

Please fix the folder and commit.  If you have decided against this change please close the PR

**Pull request closed without merging**
