### PR TITLE
AMQP static analysis fixes

### PR DESCRIPTION
**Pull request by LarryOsterman**
Fixes: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4058531&view=results

### CODE REVIEW

**Review by ahsonkhan — COMMENTED** [review]
Are there any tests we'd want to add to cover the changes made here?

**Comment by LarryOsterman** [comment]
> Are there any tests we'd want to add to cover the changes made here?

I'm not 100% sure how we add tests to verify that the compiler correctly processes `__analysis_assume` statements.  If you have any suggestions, I'm more than willing to consider adding them.

The one code change replaces two aliases for a structure, but probably doesn't affect the static analysis tools.

And the uAMQP tests don't successfully run when compiled outside the uAMQP source repo, so we don't run them.

**Review by ahsonkhan — APPROVED** [review]

**Pull request merged**
