### PR TITLE
Disable default features in libxml2.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
We don't seem to make use of any of them in `xml_wrapper.cpp`.

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [X] No unwanted commits/changes
- [X] Descriptive title/description
  - [X] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [X] Update changelog
- [X] Not work-in-progress
- [ ] External references or docs updated
- [X] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@teo-tsirpanis can you please help me understand what the consequences are of disabling default features from a dependency like libxml2 and why it's beneficial to do so?

Also, regarding:
> We don't seem to make use of any of them in xml_wrapper.cpp.

How did you check and validate that to be true? Maybe we can apply that approach elsewhere too, if useful.

**Review by antkmsft — APPROVED** [review]
Thank you @teo-tsirpanis! The change makes sense, and looks good.
I am approving, but I'll also wait for the Storage team's approval before merging.

P.S.: I pushed a commit into your branch, to also include the "Acknowledgments" section.

**Comment by Jinming-Hu** [comment]
Is there any way to test this? I tried to add


```diff
index af09fe2c5..5e13c2084 100644
--- a/ports/azure-storage-common-cpp/vcpkg.json
+++ b/ports/azure-storage-common-cpp/vcpkg.json
@@ -16,6 +16,7 @@
     },
     {
       "name": "libxml2",
+      "default-features": false,
       "platform": "!windows"
     },
     {
```

to vcpkg repo and run `./vcpkg install azure-storage-blobs-cpp`, but turned out it still installed all the features

```
The following packages will be built and installed:
  * azure-core-cpp[core,curl,http]:x64-linux -> 1.10.3#2
    azure-storage-blobs-cpp:x64-linux -> 12.10.0
  * azure-storage-common-cpp:x64-linux -> 12.5.0
  * curl[core,non-http,openssl,ssl]:x64-linux -> 8.4.0
  * libiconv:x64-linux -> 1.17#1
  * liblzma:x64-linux -> 5.4.4
  * libxml2[core,iconv,lzma,zlib]:x64-linux -> 2.11.6#1
  * openssl:x64-linux -> 3.1.4#1
  * vcpkg-cmake:x64-linux -> 2023-05-04
  * vcpkg-cmake-config:x64-linux -> 2022-02-06#1
  * vcpkg-cmake-get-vars:x64-linux -> 2023-03-02
  * zlib:x64-linux -> 1.3
```

**Review by Jinming-Hu — CHANGES_REQUESTED** [review]
I really want to test this before merging the PR.

**Comment by teo-tsirpanis** [comment]
According to vcpkg's documentation default features are not built [if the top-level project does not enable them](https://learn.microsoft.com/en-us/vcpkg/users/manifests#:~:text=if%20the%20top%2Dlevel%20project%20does%20not%20explicitly%20request%20a%20build%20without%20them).

I tried building https://github.com/teo-tsirpanis/TileDB/commit/cb672618fb2346a1bcb8b4e00d1ee15fdaebe259 and got this:

```
[cmake] Detecting compiler hash for triplet x64-linux...
[cmake] The following packages will be removed:
[cmake]     libiconv:x64-linux
[cmake]     liblzma:x64-linux
[cmake] The following packages will be built and installed:
[cmake]     azure-storage-blobs-cpp:x64-linux -> 12.10.0 -- /home/teo/code/vcpkg/buildtrees/versioning_/versions/azure-storage-blobs-cpp/902107525b099bb6c915311567519dcd55bd2aea
[cmake]   * azure-storage-common-cpp:x64-linux -> 12.5.0#1 -- /home/teo/code/TileDB/ports/azure-storage-common-cpp
[cmake]     libxml2:x64-linux -> 2.11.6#1 -- /home/teo/code/vcpkg/buildtrees/versioning_/versions/libxml2/b2fd11805c5e6714215c5dd9630400c4ad32e833
```

**Review by Jinming-Hu — APPROVED** [review]
@teo-tsirpanis @antkmsft Thanks for the pointers. I've tested this. It works for storage.

**Pull request merged**
