### PR TITLE
Fixed memory leak in curl

### PR DESCRIPTION
**Pull request by LarryOsterman**
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Review by RickWinter — APPROVED** [review]
Is there a cycle we are breaking that requires this to be defined in two places?

**Review by antkmsft — APPROVED** [review]

**Comment by LarryOsterman** [comment]
> Is there a cycle we are breaking that requires this to be defined in two places?

I only see it in a single location - sdk\core\azure-core\src\http\curl\curl_connection_private.hpp. Is it somewhere else too?

**Comment by antkmsft** [comment]
The other one is in comments, and that's probably what Rick has confused with the code. The code is in single location.

**Comment by LarryOsterman** [comment]
> The other one is in comments, and that's probably what Rick has confused with the code. The code is in single location.

Ah - of course. Yeah - there were two references to CURL and curl_free, and I didn't want to leave a stale (incorrect) reference behind.

**Review by vhvb1989 — APPROVED** [review]
Should we create an issue about improving CI gates to detect memory leaks??

**Comment by ahsonkhan** [comment]
> > The other one is in comments, and that's probably what Rick has confused with the code. The code is in single location.
> 
> Ah - of course. Yeah - there were two references to CURL and curl_free, and I didn't want to leave a stale (incorrect) reference behind.

We missed one here:
https://github.com/Azure/azure-sdk-for-cpp/blob/895a1f9f2c97d34598934979460579fb24b2298c/sdk/core/azure-core/inc/azure/core/internal/unique_handle.hpp#L58

Fixed in a follow-up PR.

**Comment by LarryOsterman** [comment]
> Should we create an issue about improving CI gates to detect memory leaks??

In my experience, automated testing for detecting memory leaks is fraught with peril. There are many false positives. And it's quite challenging to catch all memory allocations. There are usually many false positives reported.

The best way of handling them is to use RAII everywhere and then be really careful in your coding of the RAII types.

**Pull request merged**
