### PR TITLE
remove timeout patch

### PR DESCRIPTION
**Pull request by vhvb1989**
PR to check expected fail on libcurl Windows for storage tests

### CODE REVIEW

**Comment by ahsonkhan** [comment]
It doesn't seem to be failing. How come?

**Comment by vhvb1989** [comment]
> 
> 
> It doesn't seem to be failing. How come?

Well, that means that the regression we had only applies for corp net.

image


I will take a closer look later and maybe add more tests

**Comment by vhvb1989** [comment]
@ahsonkhan  I made another change to the source code expecting all libcurl usage to fail

The conclusion based on the results are good. 

image

The live tests from Storage is passing for Windows + winHttp only but failing the Windows+libcurl

**Comment by ahsonkhan** [comment]
> The live tests from Storage is passing for Windows + winHttp only but failing the Windows+libcurl

Also try the opposite please, make winhttp fail, but have libcurl succeed, on windows.

**Comment by vhvb1989** [comment]
> 
> 
> > The live tests from Storage is passing for Windows + winHttp only but failing the Windows+libcurl
> 
> Also try the opposite please, make winhttp fail, but have libcurl succeed, on windows.

I would need your help for that. I don't know how to cause a runtime error with winhttp..  Maybe not adding the host header would do it.

But, to me, that's enough with this test to confirm the expected bahavior

**Comment by ahsonkhan** [comment]
> I would need your help for that. I don't know how to cause a runtime error with winhttp.. Maybe not adding the host header would do it.

You could negate this line and cause a throw even on success:
https://github.com/Azure/azure-sdk-for-cpp/blob/a2bc2e9d99def524169f00de8353274a88cf5ad6/sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp#L324

Change it to `if (WinHttpSendRequest(`.

**Pull request closed without merging**
