### PR TITLE
Move tables tests to token only for recordings

### PR DESCRIPTION
**Pull request by gearama**
Cleaned up the tables test resource deploy script 
recordings only for keys 
non key tests only live

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Comment by LarryOsterman** [comment]
I love the idea of making the key and connection string tests LIVEONLY, it makes a TON of sense.

Have you confirmed that LIVEONLY tests are not run when AZURE_TEST_MODE is set to RECORD?

**Comment by gearama** [comment]
> I love the idea of making the key and connection string tests LIVEONLY, it makes a TON of sense.
> 
> Have you confirmed that LIVEONLY tests are not run when AZURE_TEST_MODE is set to RECORD?

Indeed i have

**Review by LarryOsterman — APPROVED** [review]

**Pull request merged**
