### PR TITLE
fix Typo in DeleteBlobResult documentation

### PR DESCRIPTION
**Pull request by microzchang**
closes https://github.com/Azure/azure-sdk-for-cpp/issues/4162

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Review by Jinming-Hu — APPROVED** [review]

**Review by antkmsft — APPROVED** [review]
I don't understand, how CI could be failing exactly at the lines that #4152 was supposed to fix? Is it possible GitHub somehow did not pull what's the latest in `main`?

**Comment by antkmsft** [comment]
@microzchang, it looks like your branch does not have the latest from main. If you merge the latest main into it, CI failure will go away.

**Comment by Jinming-Hu** [comment]
@antkmsft Don't you sleep?

**Review by ahsonkhan — APPROVED** [review]

**Comment by Jinming-Hu** [comment]
Let's merge this into main branch. It's a small change.

**Comment by microzchang** [comment]
> @microzchang, it looks like `feature/storage-dec-release` does not have the latest from `main`. If you merge the latest `main` into it (or at least the commit [7601265](https://github.com/Azure/azure-sdk-for-cpp/commit/760126502a79a08c51f787cd3a2a5a785bd90464)), CI failure will go away.

@antkmsft Thanks. I investigated yesterday why CI fails and now found the reason according to your suggestion.  I'll merge this PR to main and merge the latest main into  `feature/storage-dec-release` while this branch will be released

**Comment by antkmsft** [comment]
@Jinming-Hu I'm just on a weird sleep schedule at the moment. If I was travelling, based on the time I wake up, I should've been somewhere in the Atlantic Ocean between Portugal and Brazil :)

**Pull request closed without merging**
