### PR TITLE
Shorten the names of some long name headers

### PR DESCRIPTION
**Pull request by antkmsft**
Follow up for #4977.

This is to fix samples build which is currently blowing up on default installs.

### CODE REVIEW

**Comment by antkmsft** [comment]
@LarryOsterman, doing this would also help, correct?

**Comment by antkmsft** [comment]
@Jinming-Hu, looks good to you? There is no new code, I'm just moving from one file to another.

**Comment by LarryOsterman** [comment]
> @LarryOsterman, doing this would also help, correct?

As I mentioned in chat this morning, I think so, yes. Specifically, I suspect strongly that with these changes, I can move the checkpoint store back to the name of the package without breaking the CI pipeline. If/When this goes in, I'm going to try that.

**Review by LarryOsterman — APPROVED** [review]

**Comment by antkmsft** [comment]
@Jinming-Hu, if you have concerns with this change, please contact me or Larry.
At this point, I'm going to merge it to unblock Larry sooner.

**Pull request merged**
