### PR TITLE
CI: mac: update xcode version

### PR DESCRIPTION
**Pull request by antkmsft**

### CODE REVIEW

**Review by ahsonkhan — APPROVED** [review]

**Comment by ahsonkhan** [comment]
> Waiting on code owner review from benbp, danieljurek, and/or weshaggard

@benbp, @danieljurek, @weshaggard could one of you please approve this PR to help us unblock other changes and get CI passing? Tyvm!

**Comment by antkmsft** [comment]
@ahsonkhan, I was able to work around the approval by the CI team, your approval was enough.

**Review by danieljurek — COMMENTED** [review]
Looks like the configuration worked properly: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4190732&view=logs&j=838825d2-ae5e-5d4d-85b0-bdc7532c5664&t=b249a740-53c8-5a44-5cbf-7fc3371e705b&l=34

> Compiler found: /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++

**Pull request merged**
