### PR TITLE
Remove certain auth mechanisms within Azure Data Table Clients.

### PR DESCRIPTION
**Pull request by ahsonkhan**
Follow-up issue: https://github.com/Azure/azure-sdk-for-cpp-pr/issues/36

cc @gearama, @RickWinter

### CODE REVIEW

**Comment by gearama** [comment]
Are we sure we want to remove these connections options for customers?

**Review by gearama — COMMENTED** [review]
i would be weary about this given we have beta customers who might use the newly deleted credentials

**Comment by ahsonkhan** [comment]
Superseded by https://github.com/Azure/azure-sdk-for-cpp/pull/6181 and https://github.com/Azure/azure-sdk-for-cpp/pull/6268

**Pull request closed without merging**
