### PR TITLE
move constant definition to bottom to get around a bug in APIView tool

### PR DESCRIPTION
**Pull request by Jinming-Hu**
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/master/CONTRIBUTING.md#pull-requests).

- [x] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [x] Doxygen docs
- [x] Unit tests
- [x] No unwanted commits/changes
- [x] Descriptive title/description
  - [x] PR is single purpose
  - [x] Related issue listed
- [x] Comments in source
- [x] No typos
- [x] Update changelog
- [x] Not work-in-progress
- [x] External references or docs updated
- [x] Self review of PR done
- [x] Any breaking changes?

### CODE REVIEW

**Review by RickWinter — COMMENTED** [review]
Which bug in APIView is this working around?  I'd rather we fix that than make unwanted changes in code

**Comment by Jinming-Hu** [comment]
> Which bug in APIView is this working around? I'd rather we fix that than make unwanted changes in code

That anything in .hpp file after `_detail` namespace will be ignored. So I moved `_detail` namespace to the bottom.

**Review by vhvb1989 — APPROVED** [review]
APIView was fixed for this when we were using `details`. Then we updated the name to `_detail` and the issue came back :) .  @praveenkuttappan

**Comment by vhvb1989** [comment]
@Jinming-Hu I have created a patch for APIView so it works again: https://github.com/Azure/azure-sdk-tools/pull/1831

However, you can merge this if that unblocks you faster

**Pull request merged**
