### PR TITLE
Update sdk vcpkg portfile with VERSION and HEAD_REF

### PR DESCRIPTION
**Pull request by WangWeiLin-MV**
Update 18 sdk vcpkg `portfile.cmake`, and update `Initialize-VcpkgRelease.ps1` regex.

Reference updates PR https://github.com/microsoft/vcpkg/pull/38085 and https://github.com/microsoft/vcpkg/pull/29514 and daily validation PR https://github.com/microsoft/vcpkg/pull/34835

### Changes

* Update all 18 `sdk\**\vcpkg\portfile.cmake`
  * Append parameter `HEAD_REF` to [allow HEAD builds](https://learn.microsoft.com/en-us/vcpkg/maintainers/functions/vcpkg_from_github#head_ref) by matching `(?<=\s{4})SHA512 0\n\)` with `SHA512 0\n    HEAD_REF main\n)`
  * Replace variable `REF` to [use variable](https://learn.microsoft.com/en-us/vcpkg/maintainers/variables#version) `${VERSION}` and be quoted by matching `(?<=\s{4})REF (azure.+)@AZ_LIBRARY_VERSION@$` with `REF "$1${VERSION}"`
* Update [Initialize-VcpkgRelease.ps1#L70-L73](https://github.com/Azure/azure-sdk-for-cpp/blob/a74ecaad3dfd5f94d8c6a69209845dda294ad8ef/eng/scripts/Initialize-VcpkgRelease.ps1#L70-L73) from `REF azure.*` to `REF \"azure.*\"` to keep "Overriding REF with test release ref" for `PublishDailyVcpkg` in [archetype-cpp-release.yml#L266-L302](https://github.com/Azure/azure-sdk-for-cpp/blob/a74ecaad3dfd5f94d8c6a69209845dda294ad8ef/eng/pipelines/templates/stages/archetype-cpp-release.yml#L266-L302)

### CODE REVIEW

**Comment by antkmsft** [comment]
Thank you so much! - https://github.com/microsoft/vcpkg/pull/38085#issuecomment-2049851026

**Comment by antkmsft** [comment]
`HEAD_REF` is also a good addition. I didn't know that feature existed.
For other reviewers, this enables https://learn.microsoft.com/en-us/vcpkg/commands/install#--head

**Review by antkmsft — APPROVED** [review]
Release works as intended - https://github.com/Azure/azure-sdk-vcpkg-betas/commit/e41c4e73dc9ae91e402216b700cb9fe25e56b8ec

**Review by LarryOsterman — COMMENTED** [review]
This looks quite reasonable to me.

One small question: Why the addition of HEAD_REF?

**Review by LarryOsterman — APPROVED** [review]

**Comment by WangWeiLin-MV** [comment]
CI checks failed with `CMake` version `3.29.1` in https://github.com/microsoft/vcpkg/issues/37968.

It could be fixed by upgrading the `CMake` version in image pool to `3.29.2`, or updating the vcpkg PR https://github.com/microsoft/vcpkg/pull/38144.

**Comment by WangWeiLin-MV** [comment]
> This looks quite reasonable to me.
> 
> One small question: Why the addition of HEAD_REF?

There is a recommended optional parameter [HEAD_REF](https://learn.microsoft.com/en-us/vcpkg/maintainers/functions/vcpkg_from_github#head_ref) for `vcpkg` ports which uses `vcpkg_from_github`, it generally points the reference of git `HEAD` and here is branch `main`.

This value allows the option [--head](https://learn.microsoft.com/en-us/vcpkg/commands/install#--head) in command `vcpkg install --head ${PORT}` to fetch the latest sources available when building for ["intended for temporary testing"](https://learn.microsoft.com/en-us/vcpkg/commands/install#--head:~:text=intended%20for%20temporary%20testing).

**Pull request merged**
