### PR TITLE
[DO NOT MERGE] sample doxyfile to generate storage related docs.

### PR DESCRIPTION
**Pull request by katmsft**

### CODE REVIEW

**Comment by katmsft** [comment]
This file allows azure storage to generate it's doxygen docs. @danieljurek please check it out.

**Comment by danieljurek** [comment]
The engineering system already builds docs. The process for building docs is from the root of the repo: 

```
mkdir build
cd build 

# Most important is -DBUILD_DOCUMENTATION=YES, the others help make the build faster
cmake .. -DBUILD_DOCUMENTATION=YES -DINSTALL_GTEST=OFF -DBUILD_TESTING=OFF -DBUILD_CURL_TRANSPORT=OFF
cmake --build . --target <package-name>-docs
```

Docs are generated per-package will be built in build/sdk/{service-directory}/{package-name}/docs/html

The default doxyfile overrides we use are here: https://github.com/Azure/azure-sdk-for-cpp/blob/master/cmake-modules/doxygen_common.cmake 

If there are additional overrides that storage needs those should go in the doxygen_common.cmake file if they will work for other packages.

**Comment by katmsft** [comment]
I don't think storage needs anything special that overrides the default doc gen. This is only to show that Storage's doc is mostly ready for a doxygen output.

**Comment by RickWinter** [comment]
@katmsft Closing this PR.  Docs can be generated by running the pipeline (without publishing).  Docs can also be generated locally in a dev environment.

**Pull request closed without merging**
