### PR TITLE
Add CI pipeline step and script that validates all files in the repo contain ASCII-only bytes and no UTF-8 BOM

### PR DESCRIPTION
**Pull request by ahsonkhan**
The goal is to detect issues like this and remain green by making it a part of CI:
https://github.com/Azure/azure-sdk-for-cpp/pull/4130

This is similar to what we do in Embedded C:
https://github.com/Azure/azure-sdk-for-c/blob/cd62e2b78a396c3d5478d3b60c046adb72687274/eng/pipelines/templates/jobs/archetype-sdk-client.yml#L369-L390

### CODE REVIEW

**Review by antkmsft — APPROVED** [review]
`LibcurlTransportAdapter.md` has the `’` character. If this catches it, we're good.

**Comment by antkmsft** [comment]
It did catch `’` in the `LibcurlTransportAdapter.md`, great!

As for the errors in unit tests like `test/nlohmann-json-test/src/unit-inspection.cpp:301`: `CHECK(json("❤️").dump() == "\"❤️\"");`, if it was in our tests, I'd say we should rewrite string literals using escape characters (for example, `"❤️"` can be written as `"\u2764\uFE0F"` or as `"\xE2\x9D\xA4\xEF\xB8\x8F"`).

But given that it is in 3rd party code, CI probably should be ignoring errors in these files.

**Comment by ahsonkhan** [comment]
Yep, that's the plan. Will filter out test recordings and nlohmann json. The main focus is product/SDK code.

**Comment by antkmsft** [comment]
@ahsonkhan, if this PR is close to achieving its goal, can we get to merge it soon?

**Review by LarryOsterman — APPROVED** [review]

**Pull request merged**
