### PR TITLE
Enable UseFederatedAuth by default

### PR DESCRIPTION
**Pull request by gearama**
Had to update a test , and disable run for two samples that fail in identity. 
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Comment by gearama** [comment]
Had to disable run  2 samples since they were failing again

**Comment by weshaggard** [comment]
You should also remove UseFederatedAuth=true from any ci.yml files now https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-cpp%20UseFederatedAuth&type=code

**Comment by RickWinter** [comment]
> You should also remove UseFederatedAuth=true from any ci.yml files now https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-cpp%20UseFederatedAuth&type=code

The ones opting out will need it though, right?
UseFedereatedAuth=false

**Comment by weshaggard** [comment]
> > You should also remove UseFederatedAuth=true from any ci.yml files now https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-cpp%20UseFederatedAuth&type=code
> 
> The ones opting out will need it though, right? UseFedereatedAuth=false

Correct only the ones opting out should still have that parameter set to false.

**Review by RickWinter — APPROVED** [review]

**Comment by gearama** [comment]
@weshaggard i addressed your comments

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
