### PR TITLE
Vcpkg macro version for customers

### PR DESCRIPTION
**Pull request by vhvb1989**

### CODE REVIEW

**Review by antkmsft — COMMENTED** [review]
Can we be getting the latest by default?

**Review by LarryOsterman — APPROVED** [review]

**Review by antkmsft — APPROVED** [review]

**Comment by vhvb1989** [comment]
> Should this be completed?

done

**Comment by ahsonkhan** [comment]
@vhvb1989 what was the intended purpose of this file? What is the customer supposed to do with this? I am not sure it is needed.

It is largely a trimmed down duplicate of the file with the same name in cmake-modules, which means we have to remember to update two places whenever we make modifications.

**Pull request merged**
