### PR TITLE
remove prefer ninja

### PR DESCRIPTION
**Pull request by vhvb1989**
fixes: https://github.com/Azure/azure-sdk-for-cpp/issues/2657

### CODE REVIEW

**Review by antkmsft — APPROVED** [review]
Ha, I was going to do it myself :)
Did you test it? (if not, please wait, I can quickly verify, and then you commit)

**Comment by vhvb1989** [comment]
> Ha, I was going to do it myself :)
> Did you test it? (if not, please wait, I can quickly verify, and then you commit)

did not try it.  You know, it all about faith !  :)

**Comment by Jinming-Hu** [comment]
> it all about faith ! :)

I like this~

**Comment by antkmsft** [comment]
Thank you Victor, I tested on my local vcpkg, everything worked.

I modified files in my local vcpkg installation ports directory, removed the 🐱‍👤 ninja preference.

Be it ninja or someone else who does the job, should not matter, I thought.
So I closed my eyes hoping for the best, and started installation of azure SDK, ready to accept any outcome, be it ninja or an army of robots.

I think I have heard some katanas clashing, but it could all be my imagination. I promised I'll keep my eyes shut to remain impartial.

And when I opened my eyes, I've seen
```
Building package azure-...-cpp[core]:x64-windows-static... done
Installing package azure-...-cpp[core]:x64-windows-static...
Installing package azure-...-cpp[core]:x64-windows-static... done
Elapsed time for package azure-...-cpp:x64-windows-static: 2.579 min
Total elapsed time: 14.092 min
The package azure-...-cpp:x64-windows-static provides CMake targets:
```
INSTALLATION SUCCESSFUL.

**Pull request merged**
