### PR TITLE
Update vcpkg SHA

### PR DESCRIPTION
**Pull request by antkmsft**
Fixes `abseil` vcpackage related CI failures on `macoslatest`

### CODE REVIEW

**Review by RickWinter — APPROVED** [review]

**Review by ahsonkhan — APPROVED** [review]

**Comment by antkmsft** [comment]
Don't mind these additional live pipeline failures. We know they are there due to the authentication problem which George's PR is going to fix. The reason they are here is that I started them manualy in addition to required pipelines, so that vcpkg cache gets populated, and all the subsequent runs are much faster. I hoped they would not get associated with this PR, yet they did, and I am not making a blank commit just to make them disappear from this PR. The only auto-triggered CI's were `core - cpp - ci` and `eventhubs - cpp - ci`, and they both pass. So, I am going to /check-enforcer override.

**Pull request merged**
