### PR TITLE
Readme spelling mistake: bahavior -> behavior

### PR DESCRIPTION
**Pull request by richardpark-msft**

### CODE REVIEW

**Review by ahsonkhan — APPROVED** [review]

**Comment by ahsonkhan** [comment]
Looks like we have two other instances of `bahavior` in the repo, in source comments, if you are up for fixing them up as well in this PR :)

https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-cpp+bahavior&type=code

**Comment by LarryOsterman** [comment]
We should also understand why cspell didn't catch these - possibly we need another cspell override.

**Comment by ahsonkhan** [comment]
I think cspell's en-us dictionary is allowing "bahavior" as a word.
You can see that with:
> cspell trace "bahavior"

> bah+avior * en_us*                 node_modules/@cspell/dict-en_us/en_US.trie.gz

**Comment by ahsonkhan** [comment]
> We should also understand why cspell didn't catch these - possibly we need another cspell override.

Done, similar to https://github.com/Azure/azure-sdk-for-cpp/pull/4750

**Comment by richardpark-msft** [comment]
As a result of this I'd like to be listed as "C++ Core Contributor, Richard Park".

**Pull request merged**
