### PR TITLE
exclude generated files from test-coverage

### PR DESCRIPTION
**Pull request by Jinming-Hu**
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [x] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [x] Doxygen docs
- [x] Unit tests
- [x] No unwanted commits/changes
- [x] Descriptive title/description
  - [x] PR is single purpose
  - [x] Related issue listed
- [x] Comments in source
- [x] No typos
- [x] Update changelog
- [x] Not work-in-progress
- [x] External references or docs updated
- [x] Self review of PR done
- [x] Any breaking changes?

### CODE REVIEW

**Review by microzchang — APPROVED** [review]

**Comment by LarryOsterman** [comment]
Could you help me understand why you're excluding the generated code from code coverage?

As far as I know, all the code in the client should be covered, this leaves a fairly large set of code uninspected.

**Review by LarryOsterman — CHANGES_REQUESTED** [review]
All code executed in the client should be covered by code coverage.

**Comment by Jinming-Hu** [comment]
Hi @LarryOsterman , we'd like to remove auto-generated files from code-coverage for the present because:

1. The code logic in there all follows the same pattern, like appending a query parameter, adding a header, reading header from response. If one of them works, all of them should work. Code coverage for this specific part of code doesn't reflect the real code quality.
2. Some of the branches cannot be covered. For example, reading a header from response, we first check if the header exists, then read it. This creates an if-else branch. However, some headers are always present, so one of the branch can never be covered. This makes the coverage number (and overall coverage number) falsely low.
https://github.com/Azure/azure-sdk-for-cpp/blob/dd236311193c6a3debf3b12c47f14e49a20c72c7/sdk/storage/azure-storage-blobs/src/rest_client.cpp#L4514
3. Code coverage doesn't work well for generated files (likely caused by some bugs). All the links except for rest_client_cpp can be opened and see which lines are covered and which lines are not. We cannot improve the coverage if we cannot see the details.
image
4. We got precedents of excluding source code from coverage. This sounds reasonable to me because json.hpp is copied from another open-source project (although we made many changes).
https://github.com/Azure/azure-sdk-for-cpp/blob/dd236311193c6a3debf3b12c47f14e49a20c72c7/sdk/core/azure-core/CMakeLists.txt#L166C1-L166C114

**Comment by RickWinter** [comment]
> 4. We got precedents of excluding source code from coverage. This sounds reasonable to me because json.hpp is copied from another open-source project (although we made many changes).
>    https://github.com/Azure/azure-sdk-for-cpp/blob/dd236311193c6a3debf3b12c47f14e49a20c72c7/sdk/core/azure-core/CMakeLists.txt#L166C1-L166C114

The json code is a third party library which we do NOT own.  That is different than the code being generated from the swagger file of a service.  Generated and handwritten SDK code is considered SDK code and is subject to coverage requirements.  I agree that hitting all branches can be difficult, but the generated error handling logic exists for a reason.  To test some of those scenarios may require malformed http responses from the service.  Though unlikely it could happen if the service has a bug, in which case the SDK needs to be resilient and fail gracefully.

**Pull request closed without merging**
