### PR TITLE
Use the same client-request-id for retry requests

### PR DESCRIPTION
**Pull request by Jinming-Hu**
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [x] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [x] Doxygen docs
- [x] Unit tests
- [x] No unwanted commits/changes
- [x] Descriptive title/description
  - [x] PR is single purpose
  - [x] Related issue listed
- [x] Comments in source
- [x] No typos
- [x] Update changelog
- [x] Not work-in-progress
- [x] External references or docs updated
- [x] Self review of PR done
- [x] Any breaking changes?

### CODE REVIEW

**Comment by LarryOsterman** [comment]
Client-Request-Id is set by the `RequestIdPolicy` which is in the per-call policy list, so it should be stable across retries.

Are you seeing that the `x-ms-client-request-id` value is changed across retries? If so, that points to a more serious bug in Azure Core.

**Comment by microzchang** [comment]
Should we add a unit test for this scenario? (retry with the same client request id)

**Comment by Jinming-Hu** [comment]
@LarryOsterman 

> Client-Request-Id is set by the RequestIdPolicy which is in the per-call policy list, so it should be stable across retries.

I generally agree with this. Storage sdk has a few exceptions:

1. A batch request has a client request id. Each subrequest also has its own client request id. These ids are different from each other. The id for the parent request persists across retries, but the ids for the subrequests do not.
2. Concurrent download API sends requests to download from different offset with multiple threads. These requests all have its own client-request id (the id persists across retries).
3. When downloading a large blob, the transfer of response body could be interrupted after client-side receives 200 http status code. The retry policy won't kick in because the status code indicates a successful result. In this case, storage SDK will send a new request to download from the offset where it was interrupted. The client request id should've persisted for this kind of retry because it'd be super helpful for server-side troubleshooting. Unfortunately, we generate new client request ids for this kind of retries and this is the problem I'm trying to fix in this PR.

**Comment by Jinming-Hu** [comment]
> Should we add a unit test for this scenario? (retry with the same client request id)

I definitely have tested this locally. However, to get it in unit test, we need:

1. a way to kill a TCP connection.
1. a blob that is large enough so that the download procedure won't finish until we interrupt the connection.

Unfortunately, neither is available in our unit-test framework.

**Review by LarryOsterman — APPROVED** [review]

**Pull request merged**
