### PR TITLE
Finish implementation of queued send

### LINKED ISSUE #4510: Implement Queued Send in MessageSender API.
There are two models for send supported in uAMQP: Synchronous and asynchronous.

Asynchronous sends are queued locally before being transmitted to the sender, synchronous sends are sent and block until the client has received a disposition frame for the send.

The amount of time required to wait for the disposition response may be significant and thus a reliable asynchronous send mechanism is needed to handle this case.

### PR DESCRIPTION
**Pull request by LarryOsterman**
# Implement queued send.

Fixes #4510 

This PR implements the queued send API which allows a sender to queue up messages to be sent and then wait on the individual sends to complete. 

This introduces a new templated type "`QueuedOperation`" which represents an operation which has been queued for later completion. There are two methods available on the `QueuedOperation`: `WaitForOperationResult` which blocks waiting on the queued operation to complete and `Cancel` which is used to cancel the queued operation. 

In addition, cancellation of the context provided to the WaitForOperationResult will also cancel the outstanding send at the AMQP level.

## Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Comment by LarryOsterman** [comment]
Ping :).

**Comment by ahsonkhan** [comment]
> In addition, cancellation of the context provided to the WaitForOperationResult will also cancel the outstanding send at the AMQP level.

Are we sure we want more than one way of doing cancellation here? I wonder if there are any edge cases around the two mechanisms interfering. Does Go do the same thing (asking about it specifically because it too have context for cancellation).

**Comment by LarryOsterman** [comment]
> > In addition, cancellation of the context provided to the WaitForOperationResult will also cancel the outstanding send at the AMQP level.
> 
> Are we sure we want more than one way of doing cancellation here? I wonder if there are any edge cases around the two mechanisms interfering. Does Go do the same thing (asking about it specifically because it too have context for cancellation).

It's a good question. The thing is, there are two separate mechanisms at work here:

The `QueuedOperation::Cancel` method directly uses the internal-to-uAMQP cancellation mechanism. That means it can be called at any time the queued operation is live and will cancel it immediately without waiting.

The `Azure::Core::Context::Cancel` method relies on the fact that the `QueuedOperation::WaitForOperationResult` hooks into the `AsyncOperationQueue::WaitForPolledResult` to enable checking the `Azure::Core::Context` to see if it was cancelled.  That means that it can *only* be engaged in the context of a call to WaitForOperationResult - in other words, it only takes effect once someone has decided to block waiting on the operation to complete.

The semantics of the two cancellation mechanisms are fairly different and they handle different scenarios - one applies always, the other only applies when the caller has decided it's okto block.

Honestly, if `Azure::Core::Operation` wasn't tied intimately to the HTTP stack, I think it might be an interesting choice to consider. And honestly, refactoring Operation into OperationBase to remove the HTTP dependency might be a good idea.

**Comment by LarryOsterman** [comment]
Closing this PR to reconsider if this can be done via integration with `Azure::Core::Operation` so the experience looks similar to the `Operation` experience. Even though most queued operations aren't specifically "long term", the customer experience is very similar to that of an `Operation`.

**Pull request closed without merging**
