### PR TITLE
Ignore warning C4100 on Windows for unused parameter in OpenTelemetry headers.

### PR DESCRIPTION
**Pull request by ahsonkhan**
Fixes https://github.com/Azure/azure-sdk-for-cpp/issues/4250

Should we disable 4244 and 6323 as well, like in other files?

### CODE REVIEW

**Review by antkmsft — APPROVED** [review]

**Comment by antkmsft** [comment]
> Should we disable 4244 and 6323 as well, like in other files?

Let's disable all warnings from 3rd party libraries, there's nothing we can do, so they are unactionable but they clutter the warning log.

**Comment by LarryOsterman** [comment]
> > Should we disable 4244 and 6323 as well, like in other files?
> 
> Let's disable all warnings from 3rd party libraries, there's nothing we can do, so they are unactionable but they clutter the warning log.

I agree with Anton. When we encounter warnings like this in 3rd party libraries we should disable them. But IMHO we only do it when we encounter them.

And we should probably file issues against those libraries (when possible) to get the issues resolved.

**Review by gearama — APPROVED** [review]
shoudl we hide the warnings or look into why the warnings?

**Comment by LarryOsterman** [comment]
> shoudl we hide the warnings or look into why the warnings?

When I've seen this before, it's because 3rd party code has bugs in it. Our nightly CI pipeline runs the VC analytics which find these problems, but the actual root bug is in 3rd party code.

As far as I know, the best we can do is to suppress the warnings and file issues against the 3rd pary component to get them to fix their bugs.

**Comment by ahsonkhan** [comment]
@LarryOsterman I don't see any recent pipeline runs failing with this warning treated as error. This error seems to only show up locally for me. You mentioned some of our open telemetry nightly runs are failing with the warning that I am fixing with this PR. Can you point me to one, please? Is anyone else hitting the same error?
https://dev.azure.com/azure-sdk/internal/_build?definitionId=1615&_a=summary

**Comment by ahsonkhan** [comment]
The build error is unrelated, due to a link verification error from https://github.com/Azure/azure-sdk-for-cpp/pull/4269
Resolved in https://github.com/Azure/azure-sdk-for-cpp/pull/4273/

**Pull request merged**
