### PR TITLE
Remove noexcept specifier from Context::IsCancelled()

### LINKED ISSUE #3567: Azure::Core::Context::IsCancelled is marked as noexcept, but it calls Azure::Core::Context::GetDeadline which may throw
**Describe the bug**
https://github.com/Azure/azure-sdk-for-cpp/blob/201d588b6d344cfb72350e53ec38c649d8b94344/sdk/core/azure-core/inc/azure/core/context.hpp#L236
Is marked as `noexcept`, while it calls
https://github.com/Azure/azure-sdk-for-cpp/blob/fda88bf7b8389575b9d973821efc604442e10493/sdk/core/azure-core/inc/azure/core/context.hpp#L178
which is not `noexcept`, which violates the contract.

**To Reproduce**
Run static code analysis with `noexcept` calling chain detection against azure-sdk-for-cpp
e.g. OACR

**Expected behavior**
In general, every `noexcept` function should not call non-`noexcept`.
Please help mark `GetDeadline()` as `noexcept` if it won't throw.

**Setup (please complete the following information):**
 - OS: Windows 11 (but the issue itself is platform-independent)
 - IDE : Visual Studio 2019
 - Version of the Library used: 1.0.0-beta.2 (b16ff00d98a3fa2ad7c0966462ee44068f847b0d)

**Additional context**
Our build pipeline detects this violation, it means, if `GetDeadline()` ever throws at runtime, the program would crash.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by antkmsft**
Closes #3567

### CODE REVIEW

**Comment by Jinming-Hu** [comment]
Is this a breaking change?

**Comment by antkmsft** [comment]
@Jinming-Hu, technically it is, although it is practically very unlikely that it will throw an exception (only if `system_clock::now()` returns a year below 0001, or above 58,494. Plus, if it did in the past, user app would've terminate immediately, and if you look from that standpoint, this is even an improvement, because it gives more control to handle.

**Comment by Jinming-Hu** [comment]
> @Jinming-Hu, technically it is, although it is practically very unlikely that it will throw an exception (only if `system_clock::now()` returns a year below 0001, or above 58,494. Plus, if it did in the past, user app would've terminate immediately, and if you look from that standpoint, this is even an improvement, because it gives more control to handle.

What I'm thinking is what if a customer has used this noexcept function in another noexcept function he defined, and we remove `noexcept` directive, what would happen?

**Comment by LarryOsterman** [comment]
>> @Jinming-Hu, technically it is, although it is practically very unlikely that it will throw an exception (only if system_clock::now() returns a year below 0001, or above 58,494. Plus, if it did in the past, user app would've terminate immediately, and if you look from that standpoint, this is even an improvement, because it gives more control to handle.
> What I'm thinking is what if a customer has used this noexcept function in another noexcept function he defined, and we remove noexcept directive, what would happen?

It means that `std::terminate` is called in the client's `noexcept` function instead of `std::terminate` being called in `IsCancelled`.

**Review by JeffreyRichter — APPROVED** [review]

**Review by Jinming-Hu — APPROVED** [review]

**Pull request merged**
