### PR TITLE
changelog for Core preview 6

### PR DESCRIPTION
**Pull request by vhvb1989**

### CODE REVIEW

**Review by RickWinter — APPROVED** [review]

**Comment by ahsonkhan** [comment]
Hmm

>          D:\a\_work\1\s\sdk\core\azure-core\test\ut\uuid.cpp(50,1): warning C4018: '<': signed/unsigned mismatch [D:\a\_work\1\s\build\sdk\core\azure-core\test\ut\azure-core-test.vcxproj]

**Review by antkmsft — APPROVED** [review]

**Comment by ahsonkhan** [comment]
https://github.com/Azure/azure-sdk-for-cpp/compare/9b7849c155ffd89acf9cd00152b74446287d61ef...3e543f9a736a4394030c32e3273aeaec3c72ec41

**Comment by ahsonkhan** [comment]
We should add these bug fix:
https://github.com/Azure/azure-sdk-for-cpp/pull/1620
https://github.com/Azure/azure-sdk-for-cpp/pull/1611

And the simplified header in identity:
https://github.com/Azure/azure-sdk-for-cpp/pull/1625

**Comment by antkmsft** [comment]
@ahsonkhan, ##1: `- Fixed compilation dependency for MacOS when building VcPkg.`
##2, I'd leave up to you,
##3 - I don't think is worth mentioning, that was test improvement.

**Comment by antkmsft** [comment]
@vhvb1989, would you take these updates we are discussing?

**Comment by ahsonkhan** [comment]
> I don't think is worth mentioning, that was test improvement.

Agreed, I missed it was just tests and not the addition of the simplified header itself.

**Comment by antkmsft** [comment]
@ahsonkhan, how would you phrase the changelog entry for #1611?

**Comment by ahsonkhan** [comment]
@antkmsft done in https://github.com/Azure/azure-sdk-for-cpp/pull/1645 - please review and let me know if the wording is good for both.

**Pull request merged**
