### PR TITLE
Merge main into feature/amqp.

### PR DESCRIPTION
**Pull request by LarryOsterman**
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Comment by LarryOsterman** [comment]
Ping :).

**Comment by ahsonkhan** [comment]
> /check-enforcer override

I think we should disable the `Build Validate Ubuntu20_openssl_111n` legs while we are investigating a solution to https://github.com/Azure/azure-sdk-for-cpp/issues/4485, to unblock CI pipelines and check-ins.

Do you agree @LarryOsterman and others?

**Review by ahsonkhan — APPROVED** [review]

**Comment by LarryOsterman** [comment]
> 



> > /check-enforcer override
> 
> I think we should disable the `Build Validate Ubuntu20_openssl_111n` legs while we are investigating a solution to #4485, to unblock CI pipelines and check-ins.
> 
> Do you agree @LarryOsterman and others?

I don't have a problem with making that change. I've had exactly zero luck reproducing the public environment to look at the failure locally.

**Pull request merged**
