### PR TITLE
Rename IsBufferedDownload to ShouldBufferResponse to avoid using a storage specific verb in general purpose Request object.

### PR DESCRIPTION
**Pull request by ahsonkhan**
Follow-up to https://github.com/Azure/azure-sdk-for-cpp/pull/2196#discussion_r627003594

"Download" is just one particular use case of buffering a raw response rather than streaming it, and it's specific to storage. The API name within core should be agnostic of how it just happens to be used today.

### CODE REVIEW

**Comment by ahsonkhan** [comment]
Here's the issue for adding the complementary method on RawResponse: https://github.com/Azure/azure-sdk-for-cpp/issues/2211

**Comment by ahsonkhan** [comment]
@JeffreyRichter, @RickWinter, @vhvb1989 - waiting for approval on this.

**Comment by ahsonkhan** [comment]
> This was not planned for the milestone but added after another change.

It's from https://github.com/Azure/azure-sdk-for-cpp/pull/2196 and https://github.com/Azure/azure-sdk-for-cpp/issues/2044, which are part of this milestone.

`Request::IsBufferedDownload` gives no indication that this bool only affects where and how the RawResponse is returned back to the user. This boolean is modifying the state of the returned response, whether the response should be buffered in a vector OR returned as a stream. It essentially tells whoever is processing the request to do something, hence the use of `Should`. `IsX` indicates a particular state of the object. The request isn't a buffered download.

**Review by RickWinter — APPROVED** [review]
Review with Victor before committing.

**Comment by ahsonkhan** [comment]
Got a thumbs up from Victor, offline. Thanks.

**Review by JeffreyRichter — APPROVED** [review]

**Pull request merged**
