### PR TITLE
remove unused headers from blob protocol layer

### PR DESCRIPTION
**Pull request by Jinming-Hu**
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/master/CONTRIBUTING.md#pull-requests).

- [x] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [x] Doxygen docs
- [x] Unit tests
- [x] No unwanted commits/changes
- [x] Descriptive title/description
  - [x] PR is single purpose
  - [x] Related issue listed
- [x] Comments in source
- [x] No typos
- [x] Update changelog
- [x] Not work-in-progress
- [x] External references or docs updated
- [x] Self review of PR done
- [x] Any breaking changes?

### CODE REVIEW

**Review by katmsft — APPROVED** [review]

**Comment by Jinming-Hu** [comment]
Need to fix the warnings below:

```
CSpell: Files checked: 1, Issues found: 5 in 1 files
##[warning]D:\a\_work\1\s\sdk\storage\azure-storage-blobs\inc\azure\storage\blobs\protocol\blob_rest_client.hpp:70:27 - Unknown word (sinlge)
##[warning]D:\a\_work\1\s\sdk\storage\azure-storage-blobs\inc\azure\storage\blobs\protocol\blob_rest_client.hpp:659:90 - Unknown word (rehydrated)
##[warning]D:\a\_work\1\s\sdk\storage\azure-storage-blobs\inc\azure\storage\blobs\protocol\blob_rest_client.hpp:670:28 - Unknown word (rehydrated)
##[warning]D:\a\_work\1\s\sdk\storage\azure-storage-blobs\inc\azure\storage\blobs\protocol\blob_rest_client.hpp:674:28 - Unknown word (rehydrated)
##[warning]D:\a\_work\1\s\sdk\storage\azure-storage-blobs\inc\azure\storage\blobs\protocol\blob_rest_client.hpp:1342:41 - Unknown word (rehydrated)
##[warning]Spelling errors detected. To correct false positives or learn about spell checking see: https://aka.ms/azsdk/engsys/spellcheck
```

**Pull request merged**
