### PR TITLE
This should fail due to clang format

### PR DESCRIPTION
**Pull request by vhvb1989**
related to: 
https://github.com/Azure/azure-sdk-for-cpp/pull/2697/files

and https://github.com/Azure/azure-sdk-for-cpp/issues/2699

### CODE REVIEW

**Comment by RickWinter** [comment]
What this a draft PR to check the pipeline?  If so these changes should be verified against the template package

**Comment by vhvb1989** [comment]
@danieljurek  see how the `cpp - identity - ci` and `cpp - keyvault - ci` pipelines passed when it should have failed compiling on macOS with clang.

If I make changes to azure-core, the `cpp - core - ci` is failing. But somehow, when it is identity or keyvault, the pipelines are passing.  It fails if I run it locally.

**Comment by danieljurek** [comment]
Fixed when https://github.com/Azure/azure-sdk-for-cpp/pull/2776/files merges

**Comment by danieljurek** [comment]
Build failed successfully -- https://dev.azure.com/azure-sdk/public/_build/results?buildId=1059069&view=logs&j=51bbdecf-b8c8-57b3-5444-f22dc18cafe9&t=35a3d1b9-c9a6-57f7-470a-e23a781b8c45&l=68

**Comment by vhvb1989** [comment]
Thank you @danieljurek , I am closing this now.

**Pull request closed without merging**
