### PR TITLE
Remove samples with docker.io

### PR DESCRIPTION
**Pull request by vhvb1989**
Removing the samples using docker.io to unblock CI gates

### CODE REVIEW

**Comment by weshaggard** [comment]
As of today this is just a build warning so there shouldn't be a rush here but this build warning will turn to an error by the end of june so we need to do something by then.

**Review by LarryOsterman — APPROVED** [review]

**Comment by danieljurek** [comment]
Fixes https://github.com/Azure/azure-sdk-for-cpp/issues/3652

**Comment by danieljurek** [comment]
List of approved images and guidance for migrating in open source repos: https://eng.ms/docs/more/containers-secure-supply-chain/approved-images#how-to-handle-externally-visible-dockerfiles

**Pull request merged**
