### PR TITLE
Rename the _azure_TESTING_BUILD_AMQP compile definition to the more common _azure_TESTING_BUILD.

### PR DESCRIPTION
**Pull request by ahsonkhan**
Bringing consistency across all C++ SDKs.
Fixes https://github.com/Azure/azure-sdk-for-cpp/issues/5402

### CODE REVIEW

**Review by antkmsft — APPROVED** [review]

**Comment by ahsonkhan** [comment]
@LarryOsterman is this good to merge?

**Comment by LarryOsterman** [comment]
> @LarryOsterman is this good to merge?

Aren't we removing _azure_TESTING_BUILD until after the March azure core is released?

**Comment by ahsonkhan** [comment]
This PR is mainly about bringing consistency to the name being used across all projects.

I don't think we can remove this compiler definition without a lot of test changes.

The issue you mentioned is orthogonal (around recent virtual/final changes), and I am addressing that separately.

**Comment by LarryOsterman** [comment]
> This PR is mainly about bringing consistency to the name being used across all projects.
> 
> I don't think we can remove this compiler definition without a lot of test changes.
> 
> The issue you mentioned is orthogonal (around recent virtual/final changes), and I am addressing that separately.

There is no negative consequence to keeping the name the same until we have a centrally defined definition. In fact, as I recall, the reason I added this as an eventhubs specific definition (even though it's named AMQP) was because we *didn't* have a central definition for tests.

If we had a central definition for tests, I would wholeheartedly allow the change. But until we have a central definition, these definitions are package specific. And as a package specific definition, the name should NOT collide with definitions from other packages.

**Comment by ahsonkhan** [comment]
Alright, I will close the issue as by design, won't fix.

It's good to codify this discussion as a guideline or source comment. It wasn't clear the per-package name difference was intentional.

**Pull request closed without merging**
