### PR TITLE
Be explicit when using `private` for fields and methods in classes.

### PR DESCRIPTION
**Pull request by ahsonkhan**

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@danieljurek Unrelated gtest infra failure similar to the one a couple months ago: https://github.com/Azure/azure-sdk-for-cpp/pull/1741#issuecomment-786247814

On linux:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=825884&view=logs&j=fda9a6e2-14f0-5864-d894-5f56622f20fa&t=ca19bb24-dce0-56b6-7e8c-f313cc6f504b
```text
Cloning into 'googletest-src'...
fatal: unable to access 'https://github.com/google/googletest.git/': Could not resolve host: github.com
Cloning into 'googletest-src'...
fatal: unable to access 'https://github.com/google/googletest.git/': Could not resolve host: github.com
Cloning into 'googletest-src'...
fatal: unable to access 'https://github.com/google/googletest.git/': Could not resolve host: github.com
-- Had to git clone more than once:
          3 times.
CMake Error at googletest-subbuild/googletest-populate-prefix/tmp/googletest-populate-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/google/googletest.git'

```

**Review by vhvb1989 — COMMENTED** [review]
LGTM, just wait for @antkmsft  approval.

**Review by antkmsft — COMMENTED** [review]
LGTM, but are these all instances? What about Identity? Update test code as well?

**Comment by ahsonkhan** [comment]
> LGTM, but are these all instances? What about Identity? 

No, just ones identified during api review. Got any suggestions to find them all easily?

> Update test code as well?

I didn't do an exhaustive search and didn't look at the test code at all. I am open to suggestions, or if you notice something, feel free to fix it all up :)

**Review by Jinming-Hu — APPROVED** [review]

**Pull request merged**
