### PR TITLE
Strengthen the client_secret sanitizer regex

### PR DESCRIPTION
**Pull request by ahsonkhan**
Once we do find `client_secret=`, we want to match anything up to the next `&` and redact everything in between. Therefore, it is valuable to strengthen the regex and include all non-`&` characters, even if they may not be strictly part of the valid character set.

The goal of the sanitizer isn't to validate correctness.

Brings consistency with other languages, like Java:
https://github.com/Azure/azure-sdk-for-java/pull/39476

cc @Jinming-Hu, @microzchang, @billwert

### CODE REVIEW

**Comment by Jinming-Hu** [comment]
@ahsonkhan I'd like to test this first. Can you hold on merging for a few days?

**Review by antkmsft — APPROVED** [review]

**Review by antkmsft — COMMENTED** [review]
I agree with the change - it should work with `x-www-form-urlencoded`, and will work whether the `client_secret` is the last parameter (ends with "&"), or not. I tested with regex matcher, that it will work with both cases. This should be the regex for any parameter, when we send `x-www-form-urlencoded`, and I do not see how it can fail in that case.

https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4
```
application/x-www-form-urlencoded  
This is the default content type. Forms submitted with this
content type must be encoded as follows:

Control names and values are escaped. Space characters are
replaced by `+', and then reserved characters are escaped
as described in RFC1738, section 2.2: Non-alphanumeric
characters are replaced by `%HH', a percent sign and two
hexadecimal digits representing the ASCII code of the
character. Line breaks are represented as "CR LF" pairs
(i.e., `%0D%0A').

The control names/values are listed in the order they appear
in the document. The name is separated from the value by '='
and name/value pairs are separated from each other by `&'.
```

Looking forward, it might be good to teach sanitizer to remove parameters if we send them as `form-data` instead of `x-www-form-urlencoded` as well. Then the concrete sanitizer would be taking just the parameter name, in client_secret's case it would be just `client_secret`, and not `client_secret=`. Then, the sanitizer will analyze content-type for the request, and based on the content type, if it is `x-www-form-urlencoded`, it would apply this regex, and if it is `multipart/form-data`, it will apply something else.

**Review by billwert — APPROVED** [review]

**Review by Jinming-Hu — APPROVED** [review]
I've tested it. It works.

**Pull request merged**
