### PR TITLE
Vcpkg Beta Automation

### PR DESCRIPTION
**Pull request by danieljurek**
This PR is meant as a starting place to discuss this question, @weshaggard:  

* Given that the release process depends on an accurate baseline SHA and `git-branch-push.ps1` may rewrite history, should we bypass `git-branch-push.ps1` in this case? (I think yes)

Plenty of opportunity for refactoring. I wanted to get the question out here with an example that describes the process. 

Example release process: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1435561&view=logs&j=0a110e0c-5ffe-5151-43d9-18cd9ba97648&t=ccf1f0a9-677b-534e-3ff4-96ebeda7ff70 (note: a later step failed but it's not particularly relevant to the architectural discussion) 

Example update to vcpkg beta repo: https://github.com/Azure/azure-sdk-vcpkg-betas/commits/djurek/vcpkg-beta-automation-1

### CODE REVIEW

**Comment by danieljurek** [comment]
Some discussion: Let's tag the repo at the final commit and use the tag as the ref. This way we don't have to worry about race conditions and rewritten history.

**Comment by weshaggard** [comment]
>Given that the release process depends on an accurate baseline SHA and git-branch-push.ps1 may rewrite history, should we bypass git-branch-push.ps1 in this case? (I think yes)

It only rewrites history if you pass in "-f" option to the script otherwise if the branch isn't a fast-forward the push will fail.

**Comment by danieljurek** [comment]
> > Given that the release process depends on an accurate baseline SHA and git-branch-push.ps1 may rewrite history, should we bypass git-branch-push.ps1 in this case? (I think yes)
> 
> It only rewrites history if you pass in "-f" option to the script otherwise if the branch isn't a fast-forward the push will fail.

"Rewrite history" in my use of the terms meant that contents of the local branch will be [erased](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/git-branch-push.ps1#L139) and [replaced](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/git-branch-push.ps1#L149-L166) with similar content but the refs would be different in certain failure conditions. The history of the remote should always be intact. 

The problem here is that we have two commits: 

```
<repo history> --> Commit A --> Commit B (updates vcpkg-configuration.json to refer to Commit A)

Push fails, git diff, git reset --hard, git apply, git add, git commit results in a new set of commit SHAs: 
<repo history> --> Commit C (includes changes to vcpkg-configuration.json to refer to Commit A which is no longer part of the intended branch and might not persist in the remote) 
```

However, if we tagged the ref with a unique tag generated during the build then we could just refer to that tag: 

```
<repo history> --> Commit A (includes updates vcpkg-configuration.json to refer to Tag X) 

Push fails, remediation steps...:

<repo history> --> Commit C (includes updates vcpkg-configuration.json to refer to Tag X) 
Push succeeds 
Tag Commit C as Tag X
```

This would make the builds repeatable because tags would live on and can be applied to what was successfully pushed. 

On further thought, I think the chance of the git diff/git reset/git apply/etc. remedation workflow succeeding under normal circumstances in this process is very low given that the diff will almost always include two changes on the same line in `vcpkg-configuration.json` ... We should still defend against the possibility of automation pushing up file contents that points to a ref that's not in the final commit graph of the target branch... Another way of saying "tags are probably the way to go here"

**Comment by weshaggard** [comment]
Tags may be a good choice here but ignoring that for a minute how would you be able to handle this scenario with sha's outside of the git-branch-push.ps1? Would it require you to make new edits with the new sha when you remediate?

**Review by antkmsft — APPROVED** [review]

**Comment by danieljurek** [comment]
> Tags may be a good choice here but ignoring that for a minute how would you be able to handle this scenario with sha's outside of the git-branch-push.ps1? Would it require you to make new edits with the new sha when you remediate?

The recommended remediation strategy to start would be to re-run the pipeline today. 

To automate this process, I would start over by resetting the branch completely, pulling the latest changes, then re-running `Update-VcpkgBeta.ps1`. This would be preferred given that there could be edits to `vcpkg-configuration.json` which would result in conflict... it makes sense to incorporate the latest set of changes into the process. 

One could also extend `git-branch-push.ps1` by offering a parameter which would run a script block that could perform user-specified remediation (possibly in a loop).

**Comment by weshaggard** [comment]
>The recommended remediation strategy to start would be to re-run the pipeline today.

If you are going to fail and force a rerun wouldn't that work the same way with git-branch-push.ps1?

**Comment by danieljurek** [comment]
@weshaggard -- Unfortunately, the baseline in the file must be a "valid git commit SHA" which rules out use of a git tag... I think the double commit with a no-remediation push is the way to go here. 

```
./vcpkg install azure-template-cpp
Computing installation plan...
Fetching registry information from https://github.com/azure/azure-sdk-vcpkg-betas (HEAD)...
Error: the git registry entry for "https://github.com/azure/azure-sdk-vcpkg-betas" must have a "baseline" field that is a valid git commit SHA (40 lowercase hexadecimal characters).
The current HEAD of that repo is "612f79f9ccb38473227ee89c7c5bac15beee6922".
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

**Comment by danieljurek** [comment]
Chatted with @weshaggard ... There is a (very) small chance of a failure scenario where the push remediation work could change the commit SHA. To fix that we want to add a flag to [`git-branch-push.ps1`](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/git-branch-push.ps1) that enables us to skip the remediation procedure if the initial push fails. 

Work is tracked here: https://github.com/Azure/azure-sdk-tools/issues/3024

**Pull request merged**
