### PR TITLE
Add batch protocol layer

### PR DESCRIPTION
**Pull request by Jinming-Hu**
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [x] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [x] Doxygen docs
- [x] Unit tests
- [x] No unwanted commits/changes
- [x] Descriptive title/description
  - [x] PR is single purpose
  - [x] Related issue listed
- [x] Comments in source
- [x] No typos
- [x] Update changelog
- [x] Not work-in-progress
- [x] External references or docs updated
- [x] Self review of PR done
- [x] Any breaking changes?

redo https://github.com/Azure/azure-sdk-for-cpp/pull/3002
closes https://github.com/Azure/azure-sdk-for-cpp/issues/3000

### CODE REVIEW

**Comment by Jinming-Hu** [comment]
Hi @vhvb1989 , I redid https://github.com/Azure/azure-sdk-for-cpp/pull/3002 as part of this PR, can you approve this?

**Comment by Jinming-Hu** [comment]
@vhvb1989 can you take time to look at this PR?

**Review by vhvb1989 — APPROVED** [review]
Are you planning to merge this for Azure Core - May Release  ?

This change in Azure Core will be required by Storage, so you will need to update all the Azure Core Min Version

**Comment by Jinming-Hu** [comment]
> Are you planning to merge this for Azure Core - May Release ?

Yes

> This change in Azure Core will be required by Storage, so you will need to update all the Azure Core Min Version

Only blob package uses this new feature, so I only need to update azure core min version of blob package, is that correct?

**Comment by vhvb1989** [comment]
> > Are you planning to merge this for Azure Core - May Release ?
> 
> Yes
> 
> > This change in Azure Core will be required by Storage, so you will need to update all the Azure Core Min Version
> 
> Only blob package uses this new feature, so I only need to update azure core min version of blob package, is that correct?

IIRC, blob package uses azure-common for consuming azure-core.  So, all azure storage packages are affected, and we would want to release azure-common and azure-blobs.   You will make the choice of going beta or not for this feature.

**Comment by Jinming-Hu** [comment]
> IIRC, blob package uses azure-common for consuming azure-core. So, all azure storage packages are affected, and we would want to release azure-common and azure-blobs. You will make the choice of going beta or not for this feature.

Oh, right.

So do you have anything else to release for Azure Core SDK in May? If yes, let's just ship this feature along with that.
This is a minor change. I don't think beta release is necessary. But if you want preview other features/changes, it also works for me.

We'll ship common/blob GA release and blob batch preview release in June. I'm still trying to get things done by May, but I'm afraid it's less likely to happen)

**Pull request merged**
