### PR TITLE
Consolidate keyvault and cryptography client options and model files into single headers.

### PR DESCRIPTION
**Pull request by ahsonkhan**
Fixes https://github.com/Azure/azure-sdk-for-cpp/issues/2622

No code changes, only consolidation of options and model header files into groups.

Along with the unified header, we have a file for each client, its options, and its models.

**We now have a simpler layout:**
keyvault\keyvault_keys.hpp
keyvault\keys\dll_import_export.hpp
keyvault\keys\key_client.hpp
keyvault\keys\key_client_models.hpp
keyvault\keys\key_client_options.hpp
keyvault\keys\cryptography\cryptography_client.hpp
keyvault\keys\cryptography\cryptography_client_models.hpp
keyvault\keys\cryptography\cryptography_client_options.hpp

~If we want to, we can move the `PagedResponse<T>` and `Operation<T>`-derived classes into models as well.~

### CODE REVIEW

**Comment by gearama** [comment]
not sure about this change.
Didn't we agree yesterday to not change the headers so close to the release ? 
Without more info as to why that decision changed i cannot approve the review, as it seems we're trying to push a ~60 file change at the last second without a reason .

**Review by gearama — COMMENTED** [review]
this PR should be broken into more digestible pieces, 58 files seems excessive in any kind of PR

**Comment by ahsonkhan** [comment]
> this PR should be broken into more digestible pieces, 58 files seems excessive in any kind of PR

They are mergers of some header files into less granular header files, along with updating the #include paths. It is quite difficult to split these up into individual PRs that are meaningful on their own.

**Comment by ahsonkhan** [comment]
> Without more info as to why that decision changed i cannot approve the review, as it seems we're trying to push a ~60 file change at the last second without a reason .

We discussed this in stand up today, and the consolidation of headers (to avoid one type per header) aligns with what C++ STL libraries do, and recommend as a general pattern for C++ libraries.

**Comment by gearama** [comment]
they can be broken by area of responsibility, the PRs issued one at a time and merged individually.
I doubt anyone can actually review it, and any approval be more more than just a rubber stamp. 
Even if the change is simple there are too many edits involved for any one person to keep track of all of them,

**Comment by ahsonkhan** [comment]
> they can be broken by area of responsibility, the PRs issued one at a time and merged individually.

Can you give me an example of how you'd like it to be split?

**Comment by gearama** [comment]
one for the models, one for the operations, etc. you can slice it and dice it different ways, at the end of the day i have not requested changes in the the PR and and not blocking the merge if someone else approves so be it. i'm just voicing my concern regarding the scope and size of this PR in particular.

**Comment by ahsonkhan** [comment]
To increase confidence in this change (which doesn't have any source/implementation change), here's the APIview diff, which is easier to review and has no difference before and after (other than the re-ordering artifact) APIviewafter:https://apiview.dev/Assemblies/Review/c12e00c846994ec69a018bbcbee2f108?diffRevisionId=822405d61d5f47468d3442703de1efa2&doc=False&diffOnly=False#Azure::Security::KeyVault::Keys

And code coverage numbers (line and branch coverage) are identical.

**Comment by vhvb1989** [comment]
move operations to models. There's no benefit for keeping the operations as something different. It is just another model.

**Comment by vhvb1989** [comment]
Mode page responses to models.  If we are creating a models header, I would expect all returned types in there.  Not having some types in models brings the question of `is it not a model?`

**Comment by vhvb1989** [comment]
move 
keyvault\keys\cryptography\cryptography_client_options.hpp
keyvault\keys\cryptography\decrypt_parameters.hpp
keyvault\keys\cryptography\encrypt_parameters.hpp

to 
keyvault\keys\cryptography\cryptography_client_models.hpp

**Comment by ahsonkhan** [comment]
I thought about doing those (as a second pass), but wanted to get your take first. 

If we ever expect those to grow in different ways, we can always "de-consolidate" them in the future, so I think your suggestion is good.

**Comment by ahsonkhan** [comment]
> move operations to models. There's no benefit for keeping the operations as something different. It is just another model.

Oh, I remember now, Both LROs and PagedResponse types forward declare `KeyClient` to avoid a circular dependency (as they use it in private members). That's why I left them out of the model types.

**Comment by vhvb1989** [comment]
> > move operations to models. There's no benefit for keeping the operations as something different. It is just another model.
> 
> Oh, I remember now, Both LROs and PagedResponse types forward declare `KeyClient` to avoid a circular dependency (as they use it in private members). That's why I left them out of the model types.

It is confusing to see them out of models. When I first read the name of the header, I was not sure what it was and later I was wondering why is it not in models. Don't let an implementation detail guide the public API design  (the fw declaration is impl detail and should never be the reason of the API structure)

**Review by vhvb1989 — APPROVED** [review]

**Pull request merged**
