### PR TITLE
Revert "Service version const strings (#1349)"

### PR DESCRIPTION
**Pull request by Jinming-Hu**
This reverts commit e97349cd7d15381949843422ec1dd86772409f3b.

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/master/CONTRIBUTING.md#pull-requests).

- [x] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [x] Doxygen docs
- [x] Unit tests
- [x] No unwanted commits/changes
- [x] Descriptive title/description
  - [x] PR is single purpose
  - [x] Related issue listed
- [x] Comments in source
- [x] No typos
- [x] Update changelog
- [x] Not work-in-progress
- [x] External references or docs updated
- [x] Self review of PR done
- [x] Any breaking changes?

### CODE REVIEW

**Comment by ahsonkhan** [comment]
Reverts https://github.com/Azure/azure-sdk-for-cpp/pull/1349

**Comment by ahsonkhan** [comment]
What's motivating the revert? Re-open https://github.com/Azure/azure-sdk-for-cpp/issues/1056?

**Comment by Jinming-Hu** [comment]
> What's motivating the revert? Re-open #1056?

I feel the way I did it might be different from what Jeffrey suggests. We're planning a release today. To avoid a breaking change in the next release, i'm gonna revert this change and discuss it and add it later in the next release.

**Review by katmsft — APPROVED** [review]

**Pull request merged**
