### PR TITLE
Moving GetRawResponseInternal out of public from Operation derived classes

### PR DESCRIPTION
**Pull request by vhvb1989**
GetRawResponseInternal is not expected to be a public method from Operations.

GetRawResponse is already public in base-class Operation.

### CODE REVIEW

**Review by RickWinter — APPROVED** [review]

**Comment by ahsonkhan** [comment]
@Azure/azure-sdk-eng The CI pipelines are running in AzDo, but GitHub isn't being updated. This has been an issue for the last day or so and looks to impact other repos too. Any ideas what's causing this?

**Review by ahsonkhan — APPROVED** [review]

**Comment by weshaggard** [comment]
@ahsonkhan there was an issue with our DevOps instance it has been resolved now.

**Pull request merged**
