### PR TITLE
Workaround issue with cmake 3.29.1

### PR DESCRIPTION
**Pull request by danieljurek**

### CODE REVIEW

**Review by LarryOsterman — APPROVED** [review]
My only concern is how we deal with no longer needing the workaround. And how we remove it, since we don't really have a way of verifying that the cmake version we got from kitware is the *actual* 3.29.2 version.

**Review by antkmsft — APPROVED** [review]
This fixes the issue. I think we should check this in, it unblocks our CIs for week or two, then we drop it.
In parallel, we may start thinking if we can build some better mechanism to pin/override cmake version.

**Review by antkmsft — APPROVED** [review]

**Comment by LarryOsterman** [comment]
> @LarryOsterman, I think it fixes the issue pretty well - if we download from `https://github.com/Kitware/CMake/releases/download/v3.29.2/cmake-3.29.2-linux-x86_64.sh`, what is the chance it is not the `3.29.2` version. If in doubt, we always can double check in CI logs - we have a dedicated build step that all it does is prints cmake version.

I'm worried that someone manages to hijack the contents of that directory, and modifies the contents of that script. 

I'd be happier if we were verifying the sha256 of the script with a known published hash.

**Pull request merged**
