### PR TITLE
Make sure PRs modifying root samples and .github files within the repo get core CI triggered

### PR DESCRIPTION
**Pull request by ahsonkhan**
Follow-up from https://github.com/Azure/azure-sdk-for-cpp/pull/4544 so that things like cspell checks run within the PR that makes the changes, and avoids unrelated PRs from failing.

### CODE REVIEW

**Review by LarryOsterman — APPROVED** [review]

**Comment by LarryOsterman** [comment]
Btw, I strongly suspect this PR will fail because of the existing failure.

**Review by RickWinter — APPROVED** [review]

**Comment by RickWinter** [comment]
We'd be better off with an opt-out model.  By default have everything run the core-ci.

**Comment by ahsonkhan** [comment]
> Btw, I strongly suspect this PR will fail because of the existing failure.

Looks like it didn't fail, because **this** PR is only modifying the `ci.yml` file (and not `event-processor.yml`) and hence spell check doesn't see any errors in the files that this PR changed.

**Comment by ahsonkhan** [comment]
> We'd be better off with an opt-out model. By default have everything run the core-ci.

Would you include all the other service client SDKs on top to run core-ci as well?

Ideally, we could get to a point where the list of opt-in would be small and stable (not many root level files/folders being added). However, the list of opt-out would grow as we add more `sdk/*` folders for each new service.

**Comment by danieljurek** [comment]
Conversely we could exclude engsys related changes from spell checking in the `cspell.json` file. The goal of spell check is to ensure that the code customers use is free of spelling errors... any other spell checking is a nice to have.

**Pull request merged**
