### PR TITLE
Correct invalid UTF-8 in comment in share_options.hpp

### PR DESCRIPTION
**Pull request by Ariellink**
/storage/files/shares/share_options.hpp

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [x] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] [Any]([url]([url](url))) breaking changes?

图片
图片

### CODE REVIEW

**Review by Jinming-Hu — APPROVED** [review]

**Review by RickWinter — APPROVED** [review]

**Review by ahsonkhan — APPROVED** [review]
Thanks!

Was this the only instance you found?

**Comment by ahsonkhan** [comment]
The CI leg failures here are unrelated and will be fixed once this is merged: https://github.com/Azure/azure-sdk-for-cpp/pull/4132

**Review by antkmsft — APPROVED** [review]
`LibcurlTransportAdapter.md` also contains this character multiple times. Makes sense to fix as well?

**Comment by antkmsft** [comment]
Thank you @Ariellink!

**Pull request merged**
