### PR TITLE
Define CMakeTestOptions in Storage's ci.yml file

### PR DESCRIPTION
**Pull request by Jinming-Hu**
closes https://github.com/Azure/azure-sdk-for-cpp/issues/4774

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [x] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [x] Doxygen docs
- [x] Unit tests
- [x] No unwanted commits/changes
- [x] Descriptive title/description
  - [x] PR is single purpose
  - [x] Related issue listed
- [x] Comments in source
- [x] No typos
- [x] Update changelog
- [x] Not work-in-progress
- [x] External references or docs updated
- [x] Self review of PR done
- [x] Any breaking changes?

### CODE REVIEW

**Review by antkmsft — APPROVED** [review]

**Comment by antkmsft** [comment]
@Jinming-Hu, CI is now failing, but rightfully so. I think you should remove "`version>=`" in the manifest-mode `vcpkg.json`s - NOT the ones that are in the `vcpkg/` directories, but the ones that are in the root folder of each service library.

**Comment by antkmsft** [comment]
I updated the files I was talking about.

**Comment by Jinming-Hu** [comment]
Hi @antkmsft , what is this `vcpkg.json` for? How does it handle dependencies? Does it always install/upgrade to the latest available versions?

What if the customer has installed common v1 and blob v1. Then we release a new version of common v2 and blob v2, blob v2 depending on a new feature that is only available in common v2.
Now if the customer wants to upgrade to blob v2, without the ">=" in `vcpkg.json`, does it auto upgrade common package as well, or it will continue using common v1?

**Comment by LarryOsterman** [comment]
> Hi @antkmsft , what is this `vcpkg.json` for? How does it handle dependencies? Does it always install/upgrade to the latest available versions?
> 
> What if the customer has installed common v1 and blob v1. Then we release a new version of common v2 and blob v2, blob v2 depending on a new feature that is only available in common v2. Now if the customer wants to upgrade to blob v2, without the ">=" in `vcpkg.json`, does it auto upgrade common package as well, or it will continue using common v1?

There are two vcpkg.json files in question here.

The first `vcpkg.json` file is the package manifest, it is located in the `vcpkg` directory, and contains directives for vcpkg to use to create the vcpkg package.

The second `vcpkg.json` file is in the root of your package (sdk\storage\azure-storage\blobs for example). It is the vcpkg.json file that would be used to build the storage package if we were to build storage from that directory (rather than building from the root). This vcpkg.json is *not* used by customers. 

And yes, this is insanely confusing.

So the dependency you referenced should be in your package manifest vcpkg.json file, not the build vcpkg.json file.

The C++ project is unique among the SDK languages in that we only currently support building from the root of the repo and not building individual packages directly.

The CI pipeline checks to make sure that it is possible to run cmake from the package directory in preparation for when we enable the ability to build individual packages separate from the other packages. And that's the vcpkg.json file that Anton was referring to.

**Comment by antkmsft** [comment]
@Jinming-Hu, Larry has explained it well.

I am thinking of renaming the `azure-sdk-for-cpp/sdk/<client-library>/vcpkg/vcpkg.json` to something like `azure-sdk-for-cpp/sdk/<client-library>vcpkg/vcpkg-template.json` to remove this confusion (and also I would put `version-semver` as `99.99.999` to emphasize the diffrence, prevent people from thinking it is the real version number that needs to be incremented with releases, and to potentially say that the local version on the disk supersedes any version you may have installed via vcpkg).

As of the `azure-sdk-for-cpp/sdk/<client-library>/vcpkg.json` file, think of it as of project system file, and when we build it and it does not have any `version>=`, it means to take the current version from the cloned project tree, even if it was not released. That is in the case you loaded the project from `azure-sdk-for-cpp/CMakeLists.txt`. And if you opened the project as `azure-sdk-for-cpp/sdk/<client-library>/CMakeLists.txt`, that means the version that is available in vcpkg.

For the same reason, the "project system vcpkg.json" should not have the properly defined minimalistic dependency being put as `"default-features": false`: what is good and correct for the vcpkg release and for the users that consume vcpkg, is not suitable for day to day development work on SDK - we need effectively `"default-features": false` (i.e. since it is `true` by default, it can be dropped entirely).

Why that works: when user installs Azure SDK via vcpkg, vcpkg installs with all the default features, unless the user explicitly tells it to not install the default features. I.e. if users run `vcpkg.exe install azure-core-cpp`, it installs `vcpkg.exe install azure-core-cpp[http]`, which means `vcpkg.exe install azure-core-cpp[curl, winhttp]` on Windows, and `vcpkg.exe install azure-core-cpp[curl]` on the other platforms. That is also true when the user runs `vcpkg.exe install azure-storage-blobs-cpp`, it does install all its dependencies with the default features as well. That also works when the users consume the SDK in manifest mode and do not specify `"default-features": false`. But should user want the core with only libcurl transport implementation on Windows, they would `vcpkg.exe install azure-core-cpp[curl] azure-storage-blobs-cpp`, and the same would happen in manifest mode if they depend on `azure-core-cpp[curl]`. I.e. it is the correct way of articulating our dependency in the package manifest - "in order to be useful, we only need the bare core without any features, but should you have the core with features installed, we will work too."

But when we do this in the project mode and explicitly depend on core with `"default-features": false`, that means that it will literally install the dependency with the minimum requested set of features, i.e. without the defaults, and the minimum set of features for core is without `curl` and `winhttp` - i.e. without transport implementation at all, which is not suitable for our CI -the sources will compile, but there won't be any way to send an HTTP request.

**Pull request merged**
