### PR TITLE
Modify files by adding an extra space to trigger spell check on all files and fix any remaining issues to get the repo green

### PR DESCRIPTION
**Pull request by ahsonkhan**
Validate that the source (`*.cpp`/`*.hpp`) and markdown (`*.md`) files within the repo have spell check run on it and are all passing.

### CODE REVIEW

**Comment by RickWinter** [comment]
@ahsonkhan Is this draft still in progress or can this be closed?

**Comment by ahsonkhan** [comment]
I wanted to see how many and what kind of spelling errors/warnings we have. Let me follow-up on next steps for this PR.

**Comment by antkmsft** [comment]
@ahsonkhan, did we get what we wanted from this PR? Can it be closed?

**Comment by RickWinter** [comment]
@ahsonkhan Can this draft be closed?

**Comment by ahsonkhan** [comment]
It discovered some issues that were fixed in https://github.com/Azure/azure-sdk-for-cpp/pull/4296

And issues like:
https://github.com/Azure/azure-sdk-for-cpp/issues/4292

There are a couple other updates needed which I'll update this PR to tackle so we can merge it and **get to a complete green state** (and we need to figure out why the template CI is intermittently failing).

**Review by antkmsft — APPROVED** [review]
When you commit, if you go with the PR title as commit message, it probably will be hard to correlate the title with the actual change, so I suggest to commit as something like "Fix typo"

**Pull request merged**
