### PR TITLE
Update pipeline step to remove deprecated params in API view script

### PR DESCRIPTION
**Pull request by praveenkuttappan**
C++ has a wrapper script to generate artifact for APIView. This PR has changes to generate artifact for all packages and then use common script to send the request to APIView.

### CODE REVIEW

**Comment by praveenkuttappan** [comment]
Generated API review for template using this PR. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3614625&view=logs&j=5b596051-1552-5dd9-836c-3c8c21be24ad&t=45f4f1f2-2b1c-571a-3b86-af9bbd831265

**Comment by praveenkuttappan** [comment]
@RickWinter @LarryOsterman  FYI

**Review by LarryOsterman — COMMENTED** [review]
LGTM, but not an area expert.

**Review by danieljurek — APPROVED** [review]
API View tasks complete successfully. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3614625&view=logs&j=5b596051-1552-5dd9-836c-3c8c21be24ad&t=45f4f1f2-2b1c-571a-3b86-af9bbd831265

**Pull request merged**
